// <auto-generated />
using System;
using Infrastructure.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20221214232851_v1")]
    partial class v1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Domain.Models.Company", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Bs")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Suffix")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Companies");

                    b.HasData(
                        new
                        {
                            Id = new Guid("5e675178-d1cb-4c97-980b-5648389afe9e"),
                            Bs = "evolve compelling platforms",
                            Name = "Gibson, Gutmann and Carter",
                            Suffix = "Group"
                        },
                        new
                        {
                            Id = new Guid("08fa38a9-e2b1-48a2-a206-df2abf87de06"),
                            Bs = "embrace holistic supply-chains",
                            Name = "Feest and Sons",
                            Suffix = "LLC"
                        },
                        new
                        {
                            Id = new Guid("a67b18e2-aa15-4868-a34c-c3ebbcd6461b"),
                            Bs = "recontextualize best-of-breed applications",
                            Name = "Wilderman, Wolf and Homenick",
                            Suffix = "Group"
                        },
                        new
                        {
                            Id = new Guid("e5c539d3-714d-4e48-9950-66e026fa14cb"),
                            Bs = "streamline front-end schemas",
                            Name = "Brakus Inc",
                            Suffix = "Inc"
                        },
                        new
                        {
                            Id = new Guid("2b3ca992-c812-47f1-9995-d64bc0d0e1b6"),
                            Bs = "productize holistic markets",
                            Name = "Cruickshank - Johnston",
                            Suffix = "Inc"
                        },
                        new
                        {
                            Id = new Guid("8b3c4621-2b27-47cf-8595-f678285d7e0d"),
                            Bs = "mesh collaborative e-business",
                            Name = "Bosco, McCullough and Sanford",
                            Suffix = "Group"
                        },
                        new
                        {
                            Id = new Guid("d2f0eb69-1437-4015-8681-b2c54e4f78a5"),
                            Bs = "reintermediate real-time models",
                            Name = "Wilkinson, Walter and Ward",
                            Suffix = "LLC"
                        },
                        new
                        {
                            Id = new Guid("864981a9-6e34-4338-a66c-6c7aea051c02"),
                            Bs = "orchestrate turn-key partnerships",
                            Name = "Parisian - Smith",
                            Suffix = "LLC"
                        },
                        new
                        {
                            Id = new Guid("e85843e5-d235-49d8-b13a-8c477f77e5e1"),
                            Bs = "productize sexy technologies",
                            Name = "Heaney, Koelpin and Mitchell",
                            Suffix = "Inc"
                        },
                        new
                        {
                            Id = new Guid("67a084b0-9004-4343-8e15-05ddca6fab56"),
                            Bs = "target collaborative initiatives",
                            Name = "Wehner Group",
                            Suffix = "and Sons"
                        },
                        new
                        {
                            Id = new Guid("c5feb13c-6578-4e2a-9fef-582f26aaf0eb"),
                            Bs = "reinvent synergistic metrics",
                            Name = "Gislason LLC",
                            Suffix = "Inc"
                        },
                        new
                        {
                            Id = new Guid("b84209a6-4cc0-4c06-b86e-1d86281efb73"),
                            Bs = "e-enable interactive e-services",
                            Name = "Johnson, Pouros and Tremblay",
                            Suffix = "Inc"
                        },
                        new
                        {
                            Id = new Guid("5b28118d-d58a-421e-bbdf-ef2ad0935b1c"),
                            Bs = "innovate back-end synergies",
                            Name = "Stanton LLC",
                            Suffix = "and Sons"
                        },
                        new
                        {
                            Id = new Guid("6868e2ae-742b-4577-a2a2-8c2993cb6cec"),
                            Bs = "drive innovative models",
                            Name = "Turcotte, Swift and Zboncak",
                            Suffix = "LLC"
                        },
                        new
                        {
                            Id = new Guid("c0923acd-5973-4270-9e0c-e6c5f42f8748"),
                            Bs = "exploit customized mindshare",
                            Name = "Rohan, Abernathy and Schmeler",
                            Suffix = "and Sons"
                        },
                        new
                        {
                            Id = new Guid("93443032-880e-4a5e-9e14-3677abaab5b9"),
                            Bs = "mesh efficient e-markets",
                            Name = "Lind - Morar",
                            Suffix = "and Sons"
                        },
                        new
                        {
                            Id = new Guid("eb4479e6-7f72-4a0a-8a53-6dc1f8d94acf"),
                            Bs = "exploit vertical web-readiness",
                            Name = "Bergstrom and Sons",
                            Suffix = "Inc"
                        },
                        new
                        {
                            Id = new Guid("367412fd-1074-4e9a-bf7b-4f8652f8e2cf"),
                            Bs = "mesh next-generation convergence",
                            Name = "Klocko - Glover",
                            Suffix = "Group"
                        },
                        new
                        {
                            Id = new Guid("464a71c3-5616-4129-a3aa-e24367684e9e"),
                            Bs = "iterate seamless synergies",
                            Name = "Kessler - Hudson",
                            Suffix = "LLC"
                        },
                        new
                        {
                            Id = new Guid("c792c15a-8ebb-4909-9e27-01908239db77"),
                            Bs = "recontextualize end-to-end users",
                            Name = "Gleichner Group",
                            Suffix = "Group"
                        },
                        new
                        {
                            Id = new Guid("67cd1eb6-b79f-4a52-969c-c53e0efce9e0"),
                            Bs = "evolve bleeding-edge architectures",
                            Name = "Feest - Pfeffer",
                            Suffix = "and Sons"
                        },
                        new
                        {
                            Id = new Guid("087322da-9ae2-40ee-bcf6-846982402e9b"),
                            Bs = "matrix one-to-one synergies",
                            Name = "Breitenberg Inc",
                            Suffix = "LLC"
                        },
                        new
                        {
                            Id = new Guid("74a816b0-c060-4b75-a5be-317b6877cc85"),
                            Bs = "harness bricks-and-clicks architectures",
                            Name = "Murray, Becker and Ankunding",
                            Suffix = "LLC"
                        },
                        new
                        {
                            Id = new Guid("974a14b3-f7c7-4490-b801-cc3f6454e415"),
                            Bs = "expedite impactful bandwidth",
                            Name = "Ebert, Hauck and Schiller",
                            Suffix = "Inc"
                        },
                        new
                        {
                            Id = new Guid("06e41eee-01be-4e7e-b7eb-88971ac31e06"),
                            Bs = "whiteboard 24/365 initiatives",
                            Name = "Nienow - Marks",
                            Suffix = "LLC"
                        },
                        new
                        {
                            Id = new Guid("58ea8a9f-4ef7-45bb-bb91-f8a498f3ee80"),
                            Bs = "e-enable extensible web services",
                            Name = "West, Cormier and Williamson",
                            Suffix = "and Sons"
                        },
                        new
                        {
                            Id = new Guid("9e482ce9-ae77-483d-b126-724512acb9c1"),
                            Bs = "disintermediate front-end infomediaries",
                            Name = "Marvin and Sons",
                            Suffix = "and Sons"
                        },
                        new
                        {
                            Id = new Guid("aaf9c1f9-b607-4ddd-9cda-5d972c772240"),
                            Bs = "productize global e-services",
                            Name = "Okuneva - Lockman",
                            Suffix = "Group"
                        },
                        new
                        {
                            Id = new Guid("8d1fc1dd-60b2-4e6e-bb11-9f6cad24b0d0"),
                            Bs = "extend revolutionary action-items",
                            Name = "Hettinger - Doyle",
                            Suffix = "Group"
                        });
                });

            modelBuilder.Entity("Domain.Models.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Price")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = new Guid("4db104c7-eb7e-453d-af27-cb64d195a05e"),
                            Description = "Boston's most advanced compression wear technology increases muscle oxygenation, stabilizes active muscles",
                            Name = "Awesome Soft Pants",
                            Price = "970.97"
                        },
                        new
                        {
                            Id = new Guid("0b57a5f5-3dd5-4123-b022-161569c11e7a"),
                            Description = "The Apollotech B340 is an affordable wireless mouse with reliable connectivity, 12 months battery life and modern design",
                            Name = "Refined Plastic Soap",
                            Price = "439.01"
                        },
                        new
                        {
                            Id = new Guid("e37b035e-5593-404e-bac7-14140598ba30"),
                            Description = "The automobile layout consists of a front-engine design, with transaxle-type transmissions mounted at the rear of the engine and four wheel drive",
                            Name = "Intelligent Cotton Chips",
                            Price = "67.77"
                        },
                        new
                        {
                            Id = new Guid("ecfd61c7-fe44-4e84-ab86-a131987f8cff"),
                            Description = "New range of formal shirts are designed keeping you in mind. With fits and styling that will make you stand apart",
                            Name = "Ergonomic Granite Salad",
                            Price = "379.48"
                        },
                        new
                        {
                            Id = new Guid("18946e13-c6e0-4008-b63a-8e48581ce7e7"),
                            Description = "The Nagasaki Lander is the trademarked name of several series of Nagasaki sport bikes, that started with the 1984 ABC800J",
                            Name = "Handcrafted Granite Gloves",
                            Price = "208.01"
                        },
                        new
                        {
                            Id = new Guid("6fbc05be-8292-4298-a729-df37ccaa8685"),
                            Description = "The slim & simple Maple Gaming Keyboard from Dev Byte comes with a sleek body and 7- Color RGB LED Back-lighting for smart functionality",
                            Name = "Licensed Fresh Shoes",
                            Price = "648.55"
                        },
                        new
                        {
                            Id = new Guid("224ee556-e099-4538-887c-14abff70ac4d"),
                            Description = "New range of formal shirts are designed keeping you in mind. With fits and styling that will make you stand apart",
                            Name = "Fantastic Rubber Shirt",
                            Price = "682.85"
                        },
                        new
                        {
                            Id = new Guid("19f659cc-8dd5-4248-9f8a-e334e3030dbe"),
                            Description = "The Apollotech B340 is an affordable wireless mouse with reliable connectivity, 12 months battery life and modern design",
                            Name = "Incredible Concrete Ball",
                            Price = "811.02"
                        },
                        new
                        {
                            Id = new Guid("d44a35d3-4a63-4d92-aeff-f8d619fc5298"),
                            Description = "The Football Is Good For Training And Recreational Purposes",
                            Name = "Intelligent Metal Sausages",
                            Price = "560.51"
                        },
                        new
                        {
                            Id = new Guid("357ee24f-6d01-4a9c-b9ad-49fccc046148"),
                            Description = "New range of formal shirts are designed keeping you in mind. With fits and styling that will make you stand apart",
                            Name = "Small Cotton Car",
                            Price = "294.93"
                        },
                        new
                        {
                            Id = new Guid("1744eb6d-657f-41d7-a960-5bf66d61fd64"),
                            Description = "Carbonite web goalkeeper gloves are ergonomically designed to give easy fit",
                            Name = "Handcrafted Wooden Cheese",
                            Price = "398.52"
                        },
                        new
                        {
                            Id = new Guid("2fc52936-f7ee-4302-9b14-febdafc8e3b8"),
                            Description = "New range of formal shirts are designed keeping you in mind. With fits and styling that will make you stand apart",
                            Name = "Incredible Granite Shirt",
                            Price = "204.46"
                        },
                        new
                        {
                            Id = new Guid("8bd1fe4b-667a-4754-bb30-279f555a79a9"),
                            Description = "Carbonite web goalkeeper gloves are ergonomically designed to give easy fit",
                            Name = "Handmade Granite Cheese",
                            Price = "88.30"
                        },
                        new
                        {
                            Id = new Guid("7e5e9ee1-e4be-4f7f-af47-562a9ed9ad8c"),
                            Description = "Boston's most advanced compression wear technology increases muscle oxygenation, stabilizes active muscles",
                            Name = "Tasty Soft Gloves",
                            Price = "338.11"
                        },
                        new
                        {
                            Id = new Guid("00aab9ab-6dc0-4561-b856-a91679bda84e"),
                            Description = "The Apollotech B340 is an affordable wireless mouse with reliable connectivity, 12 months battery life and modern design",
                            Name = "Awesome Granite Chips",
                            Price = "389.18"
                        },
                        new
                        {
                            Id = new Guid("538ff381-fc46-4d8b-8102-cf29ef027c6e"),
                            Description = "Boston's most advanced compression wear technology increases muscle oxygenation, stabilizes active muscles",
                            Name = "Handcrafted Wooden Pants",
                            Price = "831.94"
                        },
                        new
                        {
                            Id = new Guid("0e9e882d-3fc9-47f1-9c00-08bb53583643"),
                            Description = "Andy shoes are designed to keeping in mind durability as well as trends, the most stylish range of shoes & sandals",
                            Name = "Handmade Concrete Chips",
                            Price = "555.55"
                        },
                        new
                        {
                            Id = new Guid("f97108b5-3a20-4eed-9e1a-b1d4974288e0"),
                            Description = "The slim & simple Maple Gaming Keyboard from Dev Byte comes with a sleek body and 7- Color RGB LED Back-lighting for smart functionality",
                            Name = "Gorgeous Frozen Bacon",
                            Price = "462.57"
                        },
                        new
                        {
                            Id = new Guid("37e073fa-a9cd-4b05-a416-fb1e0e7e5864"),
                            Description = "Ergonomic executive chair upholstered in bonded black leather and PVC padded seat and back for all-day comfort and support",
                            Name = "Gorgeous Steel Sausages",
                            Price = "731.11"
                        },
                        new
                        {
                            Id = new Guid("ef390618-799a-48e6-938a-deb08d7b4b39"),
                            Description = "Ergonomic executive chair upholstered in bonded black leather and PVC padded seat and back for all-day comfort and support",
                            Name = "Fantastic Rubber Bacon",
                            Price = "376.21"
                        },
                        new
                        {
                            Id = new Guid("aad90b54-6a6e-48c2-beae-785ed37e3c43"),
                            Description = "Ergonomic executive chair upholstered in bonded black leather and PVC padded seat and back for all-day comfort and support",
                            Name = "Rustic Wooden Fish",
                            Price = "225.39"
                        },
                        new
                        {
                            Id = new Guid("aca30ad4-cecb-4fa8-8ee0-ac3806382217"),
                            Description = "The Apollotech B340 is an affordable wireless mouse with reliable connectivity, 12 months battery life and modern design",
                            Name = "Generic Frozen Hat",
                            Price = "564.01"
                        },
                        new
                        {
                            Id = new Guid("e5725c22-c906-4c51-b524-42e9405b2b7b"),
                            Description = "The Nagasaki Lander is the trademarked name of several series of Nagasaki sport bikes, that started with the 1984 ABC800J",
                            Name = "Gorgeous Steel Salad",
                            Price = "182.94"
                        },
                        new
                        {
                            Id = new Guid("223607a2-4169-4584-98d9-ac143778f2cc"),
                            Description = "New range of formal shirts are designed keeping you in mind. With fits and styling that will make you stand apart",
                            Name = "Generic Soft Chips",
                            Price = "85.59"
                        },
                        new
                        {
                            Id = new Guid("1863203a-ff67-4f9b-98d2-a36f376058ff"),
                            Description = "New ABC 13 9370, 13.3, 5th Gen CoreA5-8250U, 8GB RAM, 256GB SSD, power UHD Graphics, OS 10 Home, OS Office A & J 2016",
                            Name = "Unbranded Wooden Bike",
                            Price = "368.22"
                        },
                        new
                        {
                            Id = new Guid("8d1ff29d-fb0e-47da-9b54-5ca7a2d4e08d"),
                            Description = "The Football Is Good For Training And Recreational Purposes",
                            Name = "Tasty Soft Chicken",
                            Price = "153.19"
                        },
                        new
                        {
                            Id = new Guid("88dc51d0-e6bf-49ca-91ef-ce2b71af2cf3"),
                            Description = "Carbonite web goalkeeper gloves are ergonomically designed to give easy fit",
                            Name = "Licensed Rubber Fish",
                            Price = "569.82"
                        },
                        new
                        {
                            Id = new Guid("8490589a-e306-4f79-a70b-5dc966e11b11"),
                            Description = "The automobile layout consists of a front-engine design, with transaxle-type transmissions mounted at the rear of the engine and four wheel drive",
                            Name = "Handmade Fresh Cheese",
                            Price = "469.91"
                        },
                        new
                        {
                            Id = new Guid("4ddada47-032c-4e54-a3d9-17919fb59886"),
                            Description = "Carbonite web goalkeeper gloves are ergonomically designed to give easy fit",
                            Name = "Sleek Cotton Chicken",
                            Price = "79.74"
                        },
                        new
                        {
                            Id = new Guid("3b25fc13-4dc3-4806-8405-f5a1333e3142"),
                            Description = "New ABC 13 9370, 13.3, 5th Gen CoreA5-8250U, 8GB RAM, 256GB SSD, power UHD Graphics, OS 10 Home, OS Office A & J 2016",
                            Name = "Fantastic Rubber Gloves",
                            Price = "778.25"
                        },
                        new
                        {
                            Id = new Guid("f8518778-883b-401a-a5c1-61541e26b198"),
                            Description = "The Football Is Good For Training And Recreational Purposes",
                            Name = "Incredible Wooden Bike",
                            Price = "876.40"
                        },
                        new
                        {
                            Id = new Guid("5ae9b679-8b22-4cdc-bb6d-e7762f69452b"),
                            Description = "Ergonomic executive chair upholstered in bonded black leather and PVC padded seat and back for all-day comfort and support",
                            Name = "Unbranded Rubber Soap",
                            Price = "358.21"
                        },
                        new
                        {
                            Id = new Guid("8fb10ed6-179b-4936-98d5-4cb36d04e7f2"),
                            Description = "The beautiful range of Apple Naturalé that has an exciting mix of natural ingredients. With the Goodness of 100% Natural Ingredients",
                            Name = "Gorgeous Frozen Towels",
                            Price = "585.34"
                        },
                        new
                        {
                            Id = new Guid("93495421-e6be-4d04-8d90-adea0cc2130f"),
                            Description = "Ergonomic executive chair upholstered in bonded black leather and PVC padded seat and back for all-day comfort and support",
                            Name = "Awesome Plastic Bike",
                            Price = "680.21"
                        },
                        new
                        {
                            Id = new Guid("606bd2e0-b979-4fc7-b77b-7b64d26d333a"),
                            Description = "The automobile layout consists of a front-engine design, with transaxle-type transmissions mounted at the rear of the engine and four wheel drive",
                            Name = "Handmade Granite Soap",
                            Price = "6.76"
                        },
                        new
                        {
                            Id = new Guid("7e5cf05a-dc4c-4b71-950a-844045a464c5"),
                            Description = "The Football Is Good For Training And Recreational Purposes",
                            Name = "Small Wooden Shirt",
                            Price = "846.20"
                        },
                        new
                        {
                            Id = new Guid("e34d65da-39bb-4ba5-ae35-fb049edaff1c"),
                            Description = "The Nagasaki Lander is the trademarked name of several series of Nagasaki sport bikes, that started with the 1984 ABC800J",
                            Name = "Practical Soft Chips",
                            Price = "709.23"
                        },
                        new
                        {
                            Id = new Guid("e986ac6e-1157-4734-a602-afc671afb54e"),
                            Description = "Boston's most advanced compression wear technology increases muscle oxygenation, stabilizes active muscles",
                            Name = "Intelligent Fresh Shirt",
                            Price = "401.25"
                        },
                        new
                        {
                            Id = new Guid("79a8cf25-ac4c-4a8a-97ec-99f331154194"),
                            Description = "Carbonite web goalkeeper gloves are ergonomically designed to give easy fit",
                            Name = "Refined Concrete Soap",
                            Price = "377.40"
                        },
                        new
                        {
                            Id = new Guid("dc31a946-b67d-4b0e-bfdd-e2548bcc3280"),
                            Description = "Andy shoes are designed to keeping in mind durability as well as trends, the most stylish range of shoes & sandals",
                            Name = "Licensed Rubber Chicken",
                            Price = "771.04"
                        },
                        new
                        {
                            Id = new Guid("cfa5f6fb-238d-4aa6-bd24-7f4b2cec924a"),
                            Description = "The slim & simple Maple Gaming Keyboard from Dev Byte comes with a sleek body and 7- Color RGB LED Back-lighting for smart functionality",
                            Name = "Ergonomic Cotton Soap",
                            Price = "563.57"
                        },
                        new
                        {
                            Id = new Guid("a2517141-ccd4-4a85-b2ff-86f2629377cb"),
                            Description = "The Apollotech B340 is an affordable wireless mouse with reliable connectivity, 12 months battery life and modern design",
                            Name = "Handcrafted Frozen Shoes",
                            Price = "879.76"
                        },
                        new
                        {
                            Id = new Guid("baa8e85f-1e68-4c5d-be2b-759a6b261c5c"),
                            Description = "The Nagasaki Lander is the trademarked name of several series of Nagasaki sport bikes, that started with the 1984 ABC800J",
                            Name = "Handmade Rubber Mouse",
                            Price = "612.84"
                        },
                        new
                        {
                            Id = new Guid("92e427fd-a827-4a1a-a620-4efbab65de5f"),
                            Description = "Ergonomic executive chair upholstered in bonded black leather and PVC padded seat and back for all-day comfort and support",
                            Name = "Ergonomic Granite Ball",
                            Price = "734.71"
                        },
                        new
                        {
                            Id = new Guid("2b610a73-47b2-4758-ba81-de0388d88381"),
                            Description = "New ABC 13 9370, 13.3, 5th Gen CoreA5-8250U, 8GB RAM, 256GB SSD, power UHD Graphics, OS 10 Home, OS Office A & J 2016",
                            Name = "Unbranded Granite Tuna",
                            Price = "443.26"
                        },
                        new
                        {
                            Id = new Guid("1db124f6-d1ef-42a0-9777-f695814d7556"),
                            Description = "Andy shoes are designed to keeping in mind durability as well as trends, the most stylish range of shoes & sandals",
                            Name = "Tasty Soft Ball",
                            Price = "792.25"
                        },
                        new
                        {
                            Id = new Guid("2396dd29-aed9-46b2-a7bf-ba3d202d2102"),
                            Description = "New range of formal shirts are designed keeping you in mind. With fits and styling that will make you stand apart",
                            Name = "Sleek Frozen Chips",
                            Price = "655.69"
                        },
                        new
                        {
                            Id = new Guid("13b32678-884a-4563-a162-4078a2574e7b"),
                            Description = "Andy shoes are designed to keeping in mind durability as well as trends, the most stylish range of shoes & sandals",
                            Name = "Rustic Concrete Hat",
                            Price = "946.46"
                        },
                        new
                        {
                            Id = new Guid("e24ac1b7-3a7e-4369-b513-323c6ebae386"),
                            Description = "The Nagasaki Lander is the trademarked name of several series of Nagasaki sport bikes, that started with the 1984 ABC800J",
                            Name = "Practical Fresh Bacon",
                            Price = "388.90"
                        },
                        new
                        {
                            Id = new Guid("722d5f2e-fab2-4e92-91ac-c1a2dbf73fde"),
                            Description = "The Football Is Good For Training And Recreational Purposes",
                            Name = "Awesome Metal Sausages",
                            Price = "48.05"
                        },
                        new
                        {
                            Id = new Guid("3939d97b-2cf8-41c3-8d15-18857ff6c05a"),
                            Description = "Boston's most advanced compression wear technology increases muscle oxygenation, stabilizes active muscles",
                            Name = "Handcrafted Fresh Chair",
                            Price = "342.63"
                        },
                        new
                        {
                            Id = new Guid("506a87a3-e28c-4d2e-9fe8-f0db8800b443"),
                            Description = "The beautiful range of Apple Naturalé that has an exciting mix of natural ingredients. With the Goodness of 100% Natural Ingredients",
                            Name = "Ergonomic Concrete Mouse",
                            Price = "658.08"
                        },
                        new
                        {
                            Id = new Guid("290b870f-26a9-4625-a56a-94cdc3055ab5"),
                            Description = "Ergonomic executive chair upholstered in bonded black leather and PVC padded seat and back for all-day comfort and support",
                            Name = "Rustic Steel Table",
                            Price = "229.89"
                        },
                        new
                        {
                            Id = new Guid("e835dd17-a55b-4a67-bc2a-51f16faeb413"),
                            Description = "Carbonite web goalkeeper gloves are ergonomically designed to give easy fit",
                            Name = "Handmade Concrete Towels",
                            Price = "413.94"
                        },
                        new
                        {
                            Id = new Guid("ce41659c-a407-47a0-90b0-86277e88a2d5"),
                            Description = "The beautiful range of Apple Naturalé that has an exciting mix of natural ingredients. With the Goodness of 100% Natural Ingredients",
                            Name = "Tasty Plastic Chicken",
                            Price = "321.87"
                        });
                });

            modelBuilder.Entity("Domain.Models.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ExpiryDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsRevoked")
                        .HasColumnType("bit");

                    b.Property<bool>("IsUsed")
                        .HasColumnType("bit");

                    b.Property<string>("JwtId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "276af310-41ad-46ca-84b0-90fcfa1833fa",
                            Name = "Normal",
                            NormalizedName = "NORMAL"
                        },
                        new
                        {
                            Id = "3b5ddb63-bdb1-448d-93ce-6f1475b8316f",
                            Name = "Admin",
                            NormalizedName = "ADMIN"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "a966a3ce-37b1-47ac-84f0-38013fd770c7",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "0d85b82e-1fcd-4eea-bd2c-d6397e94b746",
                            Email = "Admin_Karl44@yahoo.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "karl44@yahoo.com",
                            NormalizedUserName = "KARL23",
                            PasswordHash = "AQAAAAIAAYagAAAAEKLp3efxRl6fKTC54ZXSHqTQ9muvf+IU1E/dVbFBIn3WjNGQv0pKrbb4uf/2+QaquQ==",
                            PhoneNumber = "(472) 359-2497",
                            PhoneNumberConfirmed = true,
                            SecurityStamp = "9fe7a14b-9cfc-4cae-b3de-069ec438c19f",
                            TwoFactorEnabled = true,
                            UserName = "Karl23"
                        },
                        new
                        {
                            Id = "aa95bf73-9757-4c9b-8f3c-b758c2c38810",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "64ce7e99-7df3-4ad2-9d78-81628e6a4415",
                            Email = "Normal_Sherri66@yahoo.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedEmail = "sherri66@yahoo.com",
                            NormalizedUserName = "SHERRI70",
                            PasswordHash = "AQAAAAIAAYagAAAAEEAT0rb0v6fn1SsD3LRuzJCSJOTqJJ7YvDOpBHPTl6YsVWYNE7zjDzvhyCr24dX1jg==",
                            PhoneNumber = "1-382-644-9025",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "3758033d-431e-456d-9f5e-913010e92f01",
                            TwoFactorEnabled = true,
                            UserName = "Sherri70"
                        },
                        new
                        {
                            Id = "a4541f53-5110-4e82-b078-64e85fa47e39",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "59004633-0e22-4312-923c-b9e24116faab",
                            Email = "Admin_Kristopher_Ullrich72@gmail.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedEmail = "kristopher_ullrich72@gmail.com",
                            NormalizedUserName = "KRISTOPHER.ULLRICH93",
                            PasswordHash = "AQAAAAIAAYagAAAAEDVFUGyfxZsxyjr5al+Wpsea3Rv+YMdaZCqc1mb7CD7HrgZGJ9mlbU2J823Et56/Gg==",
                            PhoneNumber = "351-535-7932",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "ef2c775a-f4cf-4db7-aa16-27616c7e4b71",
                            TwoFactorEnabled = true,
                            UserName = "Kristopher.Ullrich93"
                        },
                        new
                        {
                            Id = "70784095-2f30-4f1c-a756-bec5dee1e8fc",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "74f8c0a8-413c-4a65-8a75-91062b5179e0",
                            Email = "Normal_Amy.Feil80@yahoo.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "amy.feil80@yahoo.com",
                            NormalizedUserName = "AMY29",
                            PasswordHash = "AQAAAAIAAYagAAAAEBiXQ4fXUBwEHLpK0BgTZqs0lINE/4CiCIlsMYCt3Zzwou/9g8k2RY/p1WzRJwz7aw==",
                            PhoneNumber = "(783) 559-0706 x563",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "b8b9b82d-0fdf-4530-991e-28e5ac900603",
                            TwoFactorEnabled = true,
                            UserName = "Amy29"
                        },
                        new
                        {
                            Id = "026fac15-1476-4b34-9b63-e75bb465f7b0",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "a50849d7-689f-4c57-8b36-a40776ce2ff0",
                            Email = "Admin_Rachael.Stamm8@hotmail.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "rachael.stamm8@hotmail.com",
                            NormalizedUserName = "RACHAEL_STAMM8",
                            PasswordHash = "AQAAAAIAAYagAAAAEBdTw/+fKzUTk6TXzdrv9+opBNQyWNaf/BShdp01nz9RHrLYKZMlIwd2KO7B+6ACYg==",
                            PhoneNumber = "1-891-486-2974",
                            PhoneNumberConfirmed = true,
                            SecurityStamp = "e8a94b4e-5c95-46b7-9f88-32bf58c568de",
                            TwoFactorEnabled = true,
                            UserName = "Rachael_Stamm8"
                        },
                        new
                        {
                            Id = "1d2bb238-c5a3-4966-83f9-4103153aa849",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "312fee71-b51a-4d6b-937d-565c3e1ba4bd",
                            Email = "Normal_Harriet_Mitchell18@gmail.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedEmail = "harriet_mitchell18@gmail.com",
                            NormalizedUserName = "HARRIET_MITCHELL",
                            PasswordHash = "AQAAAAIAAYagAAAAEBecDOoagV4eRpMkQ+14/8dCqYhBEIA3w/WU9CylZNK3iJ/ir0477f6qyesBeDdVPw==",
                            PhoneNumber = "556.434.8767 x211",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "3753d9f8-5f20-41ef-bf17-3e1885a7bf1c",
                            TwoFactorEnabled = false,
                            UserName = "Harriet_Mitchell"
                        },
                        new
                        {
                            Id = "67ef2581-1b4f-4abd-8b62-8e1a11849022",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "883a4c81-84a6-4157-8562-b8a703c70858",
                            Email = "Admin_Gretchen57@gmail.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "gretchen57@gmail.com",
                            NormalizedUserName = "GRETCHEN.VOLKMAN",
                            PasswordHash = "AQAAAAIAAYagAAAAEIcMxtEveNb1E2rYI37n79OUGX5GH/aHZtJ/KJNV/OwihFaXxwPXcBZNfoxGULoqbg==",
                            PhoneNumber = "(358) 399-4011 x769",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "217e601c-ef96-463a-a209-7974c8a7adf3",
                            TwoFactorEnabled = false,
                            UserName = "Gretchen.Volkman"
                        },
                        new
                        {
                            Id = "b36129d2-ed4a-4b2b-b19a-20b65622c63a",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "bc85c77b-331d-4084-a1b6-d568f7772da7",
                            Email = "Normal_Jane_Homenick68@hotmail.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedEmail = "jane_homenick68@hotmail.com",
                            NormalizedUserName = "JANE95",
                            PasswordHash = "AQAAAAIAAYagAAAAEAnLnm9BT1x38K7n9MYtdwEdDCwgzofRq2EffXLmNVbpKn0TEs9/3hsXzI6cyg3NRg==",
                            PhoneNumber = "(262) 476-2494 x3335",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "2a704eb8-7770-4d05-93e8-c2650b9b876a",
                            TwoFactorEnabled = true,
                            UserName = "Jane95"
                        },
                        new
                        {
                            Id = "7e67b05b-7915-4b5a-918d-8b991b0a755d",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "756e5edc-3b21-45dc-920e-78364dbc7ad2",
                            Email = "Normal_Eileen_Strosin@hotmail.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedEmail = "eileen_strosin@hotmail.com",
                            NormalizedUserName = "EILEEN37",
                            PasswordHash = "AQAAAAIAAYagAAAAEDggOiXYXcuxbRJwomScZqybb89HQxjt59FjIDKvNFBxs0ygD/WVwG7HkevTnsLOIg==",
                            PhoneNumber = "961-297-2334 x43624",
                            PhoneNumberConfirmed = true,
                            SecurityStamp = "65d40f03-58a5-4e33-890a-2b6a309faf59",
                            TwoFactorEnabled = false,
                            UserName = "Eileen37"
                        },
                        new
                        {
                            Id = "7dec286b-b6c5-415c-95c8-38e616b2e8ab",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "8e6ba492-1edd-4aa4-992d-42170194bac2",
                            Email = "Normal_Lois.Watsica@gmail.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "lois.watsica@gmail.com",
                            NormalizedUserName = "LOIS_WATSICA",
                            PasswordHash = "AQAAAAIAAYagAAAAED305AJ40nul4C6dt8xIgLnW97p8anRqtTnuUnlTJS8N6fDEcdk6kJcy4MBvSdcX+w==",
                            PhoneNumber = "(890) 498-8862",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "0840cb91-a14b-4bc2-be39-68fddc74788c",
                            TwoFactorEnabled = false,
                            UserName = "Lois_Watsica"
                        },
                        new
                        {
                            Id = "b57c4607-fe11-46ae-bce5-28abaaf49a7f",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "1f3e83e4-11b4-45c0-bf17-56c8f991dd07",
                            Email = "Admin_Marty_Dach49@gmail.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "marty_dach49@gmail.com",
                            NormalizedUserName = "MARTY6",
                            PasswordHash = "AQAAAAIAAYagAAAAEEdlb1SFoLW252pFnzgX1MfkeFKc3aNwtze+r9FhmVUB3LBDRmh/BU2/giZ0IF7Tig==",
                            PhoneNumber = "(452) 390-9670 x312",
                            PhoneNumberConfirmed = true,
                            SecurityStamp = "b335a454-fe90-4f97-829d-932c24dc9c5d",
                            TwoFactorEnabled = true,
                            UserName = "Marty6"
                        },
                        new
                        {
                            Id = "a41a5699-ad31-48bf-8d8a-77967e1b58e9",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "10d61874-c608-4198-8174-7f42e15271f4",
                            Email = "Admin_Mario.Homenick@yahoo.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedEmail = "mario.homenick@yahoo.com",
                            NormalizedUserName = "MARIO21",
                            PasswordHash = "AQAAAAIAAYagAAAAED9FDeZ5N9AkpNSH202dF+ffapQenJn06cKBzYsZECU8PcY0VstsF/+Li8rwV2SXuw==",
                            PhoneNumber = "1-530-357-2152",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "08bdea7f-6f66-4eec-bda8-fda00bea8969",
                            TwoFactorEnabled = false,
                            UserName = "Mario21"
                        },
                        new
                        {
                            Id = "5d965f98-58de-4db8-b1b2-95bd11fc7869",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "b4b98dd7-d10d-46f7-bf03-0d7bf964f0b6",
                            Email = "Admin_Maggie.Daugherty15@yahoo.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "maggie.daugherty15@yahoo.com",
                            NormalizedUserName = "MAGGIE_DAUGHERTY",
                            PasswordHash = "AQAAAAIAAYagAAAAEPZpu1WnMHMGn5kFaF+ozZep+5zP40WOENA5iMk6ZvqUdpyqzN+98GdLLIzzv9mZFg==",
                            PhoneNumber = "1-545-332-6406",
                            PhoneNumberConfirmed = true,
                            SecurityStamp = "16e8d832-0585-4ad6-82c9-a5ded0348fcb",
                            TwoFactorEnabled = false,
                            UserName = "Maggie_Daugherty"
                        },
                        new
                        {
                            Id = "99cf6ee1-9d46-4bbf-8b8f-722b2b7e86d2",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "99aaf9eb-fb79-4db4-bc4d-026b3b19a397",
                            Email = "Admin_Earl_Kozey73@hotmail.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "earl_kozey73@hotmail.com",
                            NormalizedUserName = "EARL_KOZEY75",
                            PasswordHash = "AQAAAAIAAYagAAAAEPjYdsvmDgqnEOXAZmspNIadAONvuFqQnfJsACmIO5nb22kCwmkC6EwGIitLaDf1BQ==",
                            PhoneNumber = "1-774-241-9201 x9734",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "12e619da-119f-4a17-9dc0-ee53696cb3fe",
                            TwoFactorEnabled = false,
                            UserName = "Earl_Kozey75"
                        },
                        new
                        {
                            Id = "e827cf54-ae2a-4c7d-98ca-8de606576894",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "4361eb7e-975f-4e42-a952-5165dfb2655c",
                            Email = "Normal_Antoinette56@yahoo.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "antoinette56@yahoo.com",
                            NormalizedUserName = "ANTOINETTE.DENESIK84",
                            PasswordHash = "AQAAAAIAAYagAAAAEN/LnPOz0OMAWc8fr0kx3Dkg9lVQdV3p6qfsEEd2xGaGttua/ILzQeAqgSpDlhTXDw==",
                            PhoneNumber = "1-313-380-0769 x9755",
                            PhoneNumberConfirmed = true,
                            SecurityStamp = "7431b097-f080-4fd6-b22e-cba167b5c093",
                            TwoFactorEnabled = true,
                            UserName = "Antoinette.Denesik84"
                        },
                        new
                        {
                            Id = "adda5085-1106-4429-b278-0da03f3f6f9d",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "2dfab87c-651f-4249-8f50-65c1015a872c",
                            Email = "Normal_Bryan3@gmail.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedEmail = "bryan3@gmail.com",
                            NormalizedUserName = "BRYAN31",
                            PasswordHash = "AQAAAAIAAYagAAAAEJlYT6gP9NAoL7shEoxRT0XGkkDHfzHidZZevu3C/+sYm1sw1JWmzA7RvqwEBGF5/w==",
                            PhoneNumber = "(243) 427-5316",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "2b207dcd-883c-4eb5-94fe-66fc65aa4c0f",
                            TwoFactorEnabled = true,
                            UserName = "Bryan31"
                        },
                        new
                        {
                            Id = "9ed6063c-d969-4ee9-9c76-28f65c2636c9",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "7a306c00-6412-489f-b6be-e3e91f400d58",
                            Email = "Normal_Rudy57@yahoo.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedEmail = "rudy57@yahoo.com",
                            NormalizedUserName = "RUDY35",
                            PasswordHash = "AQAAAAIAAYagAAAAEE/4G0khSI4/XlKbY8aM8jTKVDUudORGOPlZPCFbhYfjlPtMQ1AONuuGaj2Aa9U/DQ==",
                            PhoneNumber = "842.281.3964",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "b0179c00-fb3d-4892-accc-43ae71c874ff",
                            TwoFactorEnabled = false,
                            UserName = "Rudy35"
                        },
                        new
                        {
                            Id = "e745a19a-2f31-4c60-b4fd-b87c8d212345",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "57167044-5ed7-4bcc-baed-bc1d19cc9bde",
                            Email = "Normal_Peter.Ferry@hotmail.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedEmail = "peter.ferry@hotmail.com",
                            NormalizedUserName = "PETER.FERRY53",
                            PasswordHash = "AQAAAAIAAYagAAAAEGtKOHRGjOJQ+hxaq/c+Ma7GYP5YUGQu4BPALkuQF+8MFlc2GOFN4DXoOvfFooNA6A==",
                            PhoneNumber = "965.915.4715",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "af2b193e-5c4e-4412-a933-5d680a8e23bf",
                            TwoFactorEnabled = false,
                            UserName = "Peter.Ferry53"
                        },
                        new
                        {
                            Id = "7d846a21-8b45-43e9-b481-3f374a4ea020",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "ff0a4aee-1bc3-4bcf-b01e-25b84215d822",
                            Email = "Normal_Jenny.Ebert@yahoo.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedEmail = "jenny.ebert@yahoo.com",
                            NormalizedUserName = "JENNY.EBERT76",
                            PasswordHash = "AQAAAAIAAYagAAAAEIU/S1et0W2SFPJ6m3ruAn+Kjkegd1y0DVDiGQhj/zSq0Z4TeV8Iw4jmOmuGkWNgqg==",
                            PhoneNumber = "1-915-887-5076 x677",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "d5a64594-266b-4bb0-b5cd-ea33afead20e",
                            TwoFactorEnabled = true,
                            UserName = "Jenny.Ebert76"
                        },
                        new
                        {
                            Id = "2538d62c-7e4a-4682-9fa7-3559198d91a6",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "4c9283b3-ede0-4839-8065-b978741688f6",
                            Email = "Admin_Guillermo_Goodwin99@yahoo.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedEmail = "guillermo_goodwin99@yahoo.com",
                            NormalizedUserName = "GUILLERMO_GOODWIN71",
                            PasswordHash = "AQAAAAIAAYagAAAAEFXtePlCVKGamq4BXpbXlJ169GU7RXt94ufBTXMKQINfNkPmh70NR5Q0MkDJiUJs/Q==",
                            PhoneNumber = "(563) 205-8011 x5682",
                            PhoneNumberConfirmed = true,
                            SecurityStamp = "f05dee61-f189-4803-9be6-4424bf748b85",
                            TwoFactorEnabled = true,
                            UserName = "Guillermo_Goodwin71"
                        },
                        new
                        {
                            Id = "2f16574a-e3e5-4783-a754-e0b222daf251",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "b29d303c-0d19-4a69-a6ad-d2f78c9a0f0b",
                            Email = "Normal_Jane3@yahoo.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "jane3@yahoo.com",
                            NormalizedUserName = "JANE5",
                            PasswordHash = "AQAAAAIAAYagAAAAEIK94Z3dZ0dh/dyUFrkeYj++SUHuez7cV9nMLrmM76QF1jVb/x4cuhYGLPMQtNfqng==",
                            PhoneNumber = "598-213-5690",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "035145c6-bfbc-4a81-a758-9fa2c023a145",
                            TwoFactorEnabled = true,
                            UserName = "Jane5"
                        },
                        new
                        {
                            Id = "07ceab4a-96e4-4a12-94c1-8ddc05efb1a6",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "6a0a8525-d17e-44b9-9fb9-8b6638c79bde",
                            Email = "Normal_Natalie22@yahoo.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedEmail = "natalie22@yahoo.com",
                            NormalizedUserName = "NATALIE.WARD93",
                            PasswordHash = "AQAAAAIAAYagAAAAEEQ5VMXfp6ZodsGmki4AZ1oD3yaiFp8CNwfMoS6B76WeqvIPJKN+QYbqf8VTPzD4ag==",
                            PhoneNumber = "460.423.8641 x15144",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "70fa813e-fca8-4c48-8446-f8310393dce4",
                            TwoFactorEnabled = false,
                            UserName = "Natalie.Ward93"
                        },
                        new
                        {
                            Id = "79b2ebc7-9531-49f8-a6cd-4eb9c1c45812",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "3a0958e2-e9ec-4e11-93a3-85fdc5037fe4",
                            Email = "Admin_Gregory.Casper73@hotmail.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedEmail = "gregory.casper73@hotmail.com",
                            NormalizedUserName = "GREGORY56",
                            PasswordHash = "AQAAAAIAAYagAAAAEA3stlTjJRBv75/SkaFxM/Z0QhabagNXcbT3feb0GUH9JKdoHMrEzBjURUPQ8zXO6Q==",
                            PhoneNumber = "1-943-600-3860 x9662",
                            PhoneNumberConfirmed = true,
                            SecurityStamp = "dff6a9b4-af17-4e87-9a5d-7c1f7a9f9843",
                            TwoFactorEnabled = true,
                            UserName = "Gregory56"
                        },
                        new
                        {
                            Id = "de20b6a4-38c3-416d-88fe-33816fa0c0c9",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "0c16b42d-16f5-480b-bbae-75f196d36a8f",
                            Email = "Admin_Lila91@gmail.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "lila91@gmail.com",
                            NormalizedUserName = "LILA.BREITENBERG39",
                            PasswordHash = "AQAAAAIAAYagAAAAEHyZVX6C++31Uuzll0f7+qH7GSzY7snfODBqiFIpMcEeJ3D3h7sSLM/SDDxSPIisNQ==",
                            PhoneNumber = "736.559.6685",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "e8cc31a0-c7bd-402a-b74c-441dac46a356",
                            TwoFactorEnabled = true,
                            UserName = "Lila.Breitenberg39"
                        },
                        new
                        {
                            Id = "829e7bdf-5df1-4c3c-b4fd-bddfbfe52783",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "d011326f-9d6b-4398-9343-922e6815a401",
                            Email = "Admin_Rick.Ratke@yahoo.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedEmail = "rick.ratke@yahoo.com",
                            NormalizedUserName = "RICK.RATKE",
                            PasswordHash = "AQAAAAIAAYagAAAAEArFJAaSnP1HJ9fmB/KoA8q2ikUFIH5br8rMchl1TQTuxuZFr7Pcc0NnYLq7fJ82Fw==",
                            PhoneNumber = "889-680-2591 x076",
                            PhoneNumberConfirmed = true,
                            SecurityStamp = "8c5a1fae-dfc3-4e13-910a-e72b178f1dce",
                            TwoFactorEnabled = true,
                            UserName = "Rick.Ratke"
                        },
                        new
                        {
                            Id = "20d9d315-549c-4e8f-8a37-bf0eee6d7796",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "e19b40fa-326b-4d77-b9e6-f78a9937447d",
                            Email = "Normal_Anthony9@yahoo.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedEmail = "anthony9@yahoo.com",
                            NormalizedUserName = "ANTHONY_PFANNERSTILL81",
                            PasswordHash = "AQAAAAIAAYagAAAAENhM4Uw2wwleVAtrbH2OcfBbUxaL0VR142D9CEZHRqzVA36erl5/HmdthfwnCbmfYg==",
                            PhoneNumber = "(707) 770-0405 x275",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "d88d0bad-e528-4e47-875f-317f6644183e",
                            TwoFactorEnabled = false,
                            UserName = "Anthony_Pfannerstill81"
                        },
                        new
                        {
                            Id = "8dd949fa-d27e-4b3e-be40-b284a6c33327",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "2a2a6ae1-3715-4297-99c6-22c7002452dd",
                            Email = "Normal_Horace_Lang@hotmail.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "horace_lang@hotmail.com",
                            NormalizedUserName = "HORACE_LANG",
                            PasswordHash = "AQAAAAIAAYagAAAAEL338igNY+T44R8raVEM/3M6mKgKXuXDNAYlUzDkwIdqQ8VMKFc8f9IY0Ka2QqB4uQ==",
                            PhoneNumber = "1-639-432-1970 x9040",
                            PhoneNumberConfirmed = true,
                            SecurityStamp = "39dface7-6722-4a6f-8c8a-e02640760a44",
                            TwoFactorEnabled = false,
                            UserName = "Horace_Lang"
                        },
                        new
                        {
                            Id = "7ae1c839-292e-4ac4-90fa-3f260007d657",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "5cbeede1-f96c-4e18-90ec-9cb6ffdca3d0",
                            Email = "Admin_Franklin_Konopelski42@yahoo.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedEmail = "franklin_konopelski42@yahoo.com",
                            NormalizedUserName = "FRANKLIN.KONOPELSKI67",
                            PasswordHash = "AQAAAAIAAYagAAAAEMpCfwAhuevmwjyVBXg9DYjSK1tuKXCRVtFXvmFhbzhnIRgTOV0cYDei5sIPG0rpog==",
                            PhoneNumber = "(412) 535-2446",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "49484cd1-b3f8-4ffe-8e82-f4d20eaa727c",
                            TwoFactorEnabled = false,
                            UserName = "Franklin.Konopelski67"
                        },
                        new
                        {
                            Id = "5760c2b7-4d08-4792-a168-933fa1c17a62",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "0bd1db5e-e787-44c5-beaf-a357c5c111b0",
                            Email = "Normal_Maggie18@hotmail.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "maggie18@hotmail.com",
                            NormalizedUserName = "MAGGIE_PARISIAN43",
                            PasswordHash = "AQAAAAIAAYagAAAAENyGdspN/cVqRoUCCamtjHpCgIG5pTKcQm/3/DPvZ9V5pU3Y5swuFEAu8HISmaxysQ==",
                            PhoneNumber = "433.345.6215 x823",
                            PhoneNumberConfirmed = true,
                            SecurityStamp = "d96d0218-0b76-4a5c-86cb-3fdf32e91fb9",
                            TwoFactorEnabled = false,
                            UserName = "Maggie_Parisian43"
                        },
                        new
                        {
                            Id = "cc57b37a-bb3a-4b2d-addd-817fbf526667",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "ad991d45-c8a1-49d1-93c2-ad549c6faa5a",
                            Email = "Normal_Saul_Carter@yahoo.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "saul_carter@yahoo.com",
                            NormalizedUserName = "SAUL_CARTER",
                            PasswordHash = "AQAAAAIAAYagAAAAECC2bFBdjx/qDrij1QDI3AbR6AhTnDPSIJ1dRX1o9dmEkMht+GMykDsPvNoQum6tTQ==",
                            PhoneNumber = "(813) 519-8288 x686",
                            PhoneNumberConfirmed = true,
                            SecurityStamp = "2dc26a25-e97d-4ca6-864e-21f55a1e1a8f",
                            TwoFactorEnabled = true,
                            UserName = "Saul_Carter"
                        },
                        new
                        {
                            Id = "ecb4066f-59c7-41c9-99e6-32e354cd507f",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "fb8a1d45-7193-494e-a619-2be87388cac3",
                            Email = "Admin_Hannah.Barrows76@gmail.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "hannah.barrows76@gmail.com",
                            NormalizedUserName = "HANNAH.BARROWS17",
                            PasswordHash = "AQAAAAIAAYagAAAAEHK/9rFaSfz+JRgijFBKsrskzscAEIdiirTSI38m40KMkX7B1dO79zaaaEKAbPA+rg==",
                            PhoneNumber = "(911) 976-8672 x660",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "acb680cb-7650-4ec0-93f6-ec34585329ab",
                            TwoFactorEnabled = false,
                            UserName = "Hannah.Barrows17"
                        },
                        new
                        {
                            Id = "fbd1a202-e0fe-4a4e-83e4-fd9b2cba7aea",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "b7fda479-c3e1-4fc6-b3ef-8be29ad700be",
                            Email = "Normal_Ernesto.Crooks31@hotmail.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "ernesto.crooks31@hotmail.com",
                            NormalizedUserName = "ERNESTO.CROOKS50",
                            PasswordHash = "AQAAAAIAAYagAAAAEP+d3DAbyYtVvaPkv/hdBbvKKo7KZKUlRUzweh3I3Kc2FYzrsL7mRHRo20xTIyKScA==",
                            PhoneNumber = "992-645-2475 x80297",
                            PhoneNumberConfirmed = true,
                            SecurityStamp = "238b137c-72aa-47ce-86e5-aa3de1f87634",
                            TwoFactorEnabled = true,
                            UserName = "Ernesto.Crooks50"
                        },
                        new
                        {
                            Id = "513f83a8-378e-44c8-9519-24dfa658f140",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "7bccff85-350e-42db-ac26-0442546e7167",
                            Email = "Admin_Lamar32@yahoo.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedEmail = "lamar32@yahoo.com",
                            NormalizedUserName = "LAMAR.MARVIN",
                            PasswordHash = "AQAAAAIAAYagAAAAECzLSLRrbtjs3oNHBNmC5ohORFnloe6dwOKHlSaopSV/Fvhd2Q9uCwHGa0xVi4zhzQ==",
                            PhoneNumber = "333.450.6704 x384",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "bbd2bf85-86cc-43c4-a696-b09043fc1e9c",
                            TwoFactorEnabled = true,
                            UserName = "Lamar.Marvin"
                        },
                        new
                        {
                            Id = "e15858e1-975c-4037-a834-191acb802e51",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "79bb9741-80c2-41e4-b22a-5601e827bb62",
                            Email = "Normal_Brandy.Stehr@gmail.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedEmail = "brandy.stehr@gmail.com",
                            NormalizedUserName = "BRANDY_STEHR",
                            PasswordHash = "AQAAAAIAAYagAAAAEAXAXUDQWTU5yFI1svFNRLa+B6MfG+4drHKzSwj7WbxFycd11C+qW50MJSCJ1ELY6g==",
                            PhoneNumber = "(678) 755-9960 x220",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "e728fdb7-4302-4673-9e11-b5b5bcf184d9",
                            TwoFactorEnabled = false,
                            UserName = "Brandy_Stehr"
                        },
                        new
                        {
                            Id = "75f0ab6f-1706-492a-9c73-247a84822fb2",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "2cad90ba-173a-4777-ac78-26a53a0198e9",
                            Email = "Normal_Orville_Rogahn94@yahoo.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedEmail = "orville_rogahn94@yahoo.com",
                            NormalizedUserName = "ORVILLE_ROGAHN",
                            PasswordHash = "AQAAAAIAAYagAAAAEOs8URblW0NB2r6X6DcvQ/WrKYmD4Fhy+v3LJ3rjyTGG5PWinrcd350LS8NKNhuwRw==",
                            PhoneNumber = "(678) 376-0073",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "2a2d0034-cda5-454f-88fd-7a3fb75c0f3e",
                            TwoFactorEnabled = false,
                            UserName = "Orville_Rogahn"
                        },
                        new
                        {
                            Id = "967760ee-6c1f-458e-a844-acb7b95fef4c",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "85743c8a-d0b2-4a39-a39a-c7b1c9adf2c3",
                            Email = "Admin_Tomas34@gmail.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedEmail = "tomas34@gmail.com",
                            NormalizedUserName = "TOMAS28",
                            PasswordHash = "AQAAAAIAAYagAAAAEASgnbU9l7VMBAuc1ftqNWHxJKXSKwWChFEvDKtKBxpon47wydg638a0r06YCrH0Aw==",
                            PhoneNumber = "(701) 666-6012",
                            PhoneNumberConfirmed = true,
                            SecurityStamp = "17d9d9b7-1ed6-46f3-8856-9c95c6e1ff52",
                            TwoFactorEnabled = false,
                            UserName = "Tomas28"
                        },
                        new
                        {
                            Id = "265bbb85-edfc-4c43-af1f-5e09164c732f",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "22fcd827-c3ed-4355-8f51-9c872be00622",
                            Email = "Normal_Norman.Carter@gmail.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedEmail = "norman.carter@gmail.com",
                            NormalizedUserName = "NORMAN_CARTER",
                            PasswordHash = "AQAAAAIAAYagAAAAEDv377AZVHuQQjv5uIJrLmV1aaxGoxho9LEB3NPLZGx7pM3sRxS0NM8UemsiEbE6vA==",
                            PhoneNumber = "1-216-262-6871 x593",
                            PhoneNumberConfirmed = true,
                            SecurityStamp = "8c11c02e-5fd7-450e-ba59-553950442b57",
                            TwoFactorEnabled = true,
                            UserName = "Norman_Carter"
                        },
                        new
                        {
                            Id = "8829499e-b67e-425f-bda0-6b9964a759da",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "659cac61-6996-4369-802a-4f6f6f33b893",
                            Email = "Admin_Tammy.Barrows91@hotmail.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "tammy.barrows91@hotmail.com",
                            NormalizedUserName = "TAMMY42",
                            PasswordHash = "AQAAAAIAAYagAAAAEBhQa6JaPbd39DBAaCm/2ApJ4aGtTu6+P+RordrjGGQUW1Id9hXY/kC6KWVH6U/DNg==",
                            PhoneNumber = "643.552.6704 x613",
                            PhoneNumberConfirmed = true,
                            SecurityStamp = "be7b9775-2b97-4e12-8b3e-30f45b61b35c",
                            TwoFactorEnabled = true,
                            UserName = "Tammy42"
                        },
                        new
                        {
                            Id = "b264f183-8818-4e65-85b4-bc040204aa7b",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "76cc14e9-5fbe-4889-a9e2-55e7476a092a",
                            Email = "Normal_Josephine8@gmail.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedEmail = "josephine8@gmail.com",
                            NormalizedUserName = "JOSEPHINE_DAUGHERTY26",
                            PasswordHash = "AQAAAAIAAYagAAAAEMCO9zHvP7teckJVztWzR2dhiKlAWZkDj5Smehx/qFdiBJvWjVrjkLYSGdFbkYoQZQ==",
                            PhoneNumber = "343.807.9756",
                            PhoneNumberConfirmed = true,
                            SecurityStamp = "78aeccbe-ac17-48ea-83ba-5699d3353312",
                            TwoFactorEnabled = true,
                            UserName = "Josephine_Daugherty26"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = "a966a3ce-37b1-47ac-84f0-38013fd770c7",
                            RoleId = "3b5ddb63-bdb1-448d-93ce-6f1475b8316f"
                        },
                        new
                        {
                            UserId = "aa95bf73-9757-4c9b-8f3c-b758c2c38810",
                            RoleId = "276af310-41ad-46ca-84b0-90fcfa1833fa"
                        },
                        new
                        {
                            UserId = "a4541f53-5110-4e82-b078-64e85fa47e39",
                            RoleId = "3b5ddb63-bdb1-448d-93ce-6f1475b8316f"
                        },
                        new
                        {
                            UserId = "70784095-2f30-4f1c-a756-bec5dee1e8fc",
                            RoleId = "276af310-41ad-46ca-84b0-90fcfa1833fa"
                        },
                        new
                        {
                            UserId = "026fac15-1476-4b34-9b63-e75bb465f7b0",
                            RoleId = "3b5ddb63-bdb1-448d-93ce-6f1475b8316f"
                        },
                        new
                        {
                            UserId = "1d2bb238-c5a3-4966-83f9-4103153aa849",
                            RoleId = "276af310-41ad-46ca-84b0-90fcfa1833fa"
                        },
                        new
                        {
                            UserId = "67ef2581-1b4f-4abd-8b62-8e1a11849022",
                            RoleId = "3b5ddb63-bdb1-448d-93ce-6f1475b8316f"
                        },
                        new
                        {
                            UserId = "b36129d2-ed4a-4b2b-b19a-20b65622c63a",
                            RoleId = "276af310-41ad-46ca-84b0-90fcfa1833fa"
                        },
                        new
                        {
                            UserId = "7e67b05b-7915-4b5a-918d-8b991b0a755d",
                            RoleId = "276af310-41ad-46ca-84b0-90fcfa1833fa"
                        },
                        new
                        {
                            UserId = "7dec286b-b6c5-415c-95c8-38e616b2e8ab",
                            RoleId = "276af310-41ad-46ca-84b0-90fcfa1833fa"
                        },
                        new
                        {
                            UserId = "b57c4607-fe11-46ae-bce5-28abaaf49a7f",
                            RoleId = "3b5ddb63-bdb1-448d-93ce-6f1475b8316f"
                        },
                        new
                        {
                            UserId = "a41a5699-ad31-48bf-8d8a-77967e1b58e9",
                            RoleId = "3b5ddb63-bdb1-448d-93ce-6f1475b8316f"
                        },
                        new
                        {
                            UserId = "5d965f98-58de-4db8-b1b2-95bd11fc7869",
                            RoleId = "3b5ddb63-bdb1-448d-93ce-6f1475b8316f"
                        },
                        new
                        {
                            UserId = "99cf6ee1-9d46-4bbf-8b8f-722b2b7e86d2",
                            RoleId = "3b5ddb63-bdb1-448d-93ce-6f1475b8316f"
                        },
                        new
                        {
                            UserId = "e827cf54-ae2a-4c7d-98ca-8de606576894",
                            RoleId = "276af310-41ad-46ca-84b0-90fcfa1833fa"
                        },
                        new
                        {
                            UserId = "adda5085-1106-4429-b278-0da03f3f6f9d",
                            RoleId = "276af310-41ad-46ca-84b0-90fcfa1833fa"
                        },
                        new
                        {
                            UserId = "9ed6063c-d969-4ee9-9c76-28f65c2636c9",
                            RoleId = "276af310-41ad-46ca-84b0-90fcfa1833fa"
                        },
                        new
                        {
                            UserId = "e745a19a-2f31-4c60-b4fd-b87c8d212345",
                            RoleId = "276af310-41ad-46ca-84b0-90fcfa1833fa"
                        },
                        new
                        {
                            UserId = "7d846a21-8b45-43e9-b481-3f374a4ea020",
                            RoleId = "276af310-41ad-46ca-84b0-90fcfa1833fa"
                        },
                        new
                        {
                            UserId = "2538d62c-7e4a-4682-9fa7-3559198d91a6",
                            RoleId = "3b5ddb63-bdb1-448d-93ce-6f1475b8316f"
                        },
                        new
                        {
                            UserId = "2f16574a-e3e5-4783-a754-e0b222daf251",
                            RoleId = "276af310-41ad-46ca-84b0-90fcfa1833fa"
                        },
                        new
                        {
                            UserId = "07ceab4a-96e4-4a12-94c1-8ddc05efb1a6",
                            RoleId = "276af310-41ad-46ca-84b0-90fcfa1833fa"
                        },
                        new
                        {
                            UserId = "79b2ebc7-9531-49f8-a6cd-4eb9c1c45812",
                            RoleId = "3b5ddb63-bdb1-448d-93ce-6f1475b8316f"
                        },
                        new
                        {
                            UserId = "de20b6a4-38c3-416d-88fe-33816fa0c0c9",
                            RoleId = "3b5ddb63-bdb1-448d-93ce-6f1475b8316f"
                        },
                        new
                        {
                            UserId = "829e7bdf-5df1-4c3c-b4fd-bddfbfe52783",
                            RoleId = "3b5ddb63-bdb1-448d-93ce-6f1475b8316f"
                        },
                        new
                        {
                            UserId = "20d9d315-549c-4e8f-8a37-bf0eee6d7796",
                            RoleId = "276af310-41ad-46ca-84b0-90fcfa1833fa"
                        },
                        new
                        {
                            UserId = "8dd949fa-d27e-4b3e-be40-b284a6c33327",
                            RoleId = "276af310-41ad-46ca-84b0-90fcfa1833fa"
                        },
                        new
                        {
                            UserId = "7ae1c839-292e-4ac4-90fa-3f260007d657",
                            RoleId = "3b5ddb63-bdb1-448d-93ce-6f1475b8316f"
                        },
                        new
                        {
                            UserId = "5760c2b7-4d08-4792-a168-933fa1c17a62",
                            RoleId = "276af310-41ad-46ca-84b0-90fcfa1833fa"
                        },
                        new
                        {
                            UserId = "cc57b37a-bb3a-4b2d-addd-817fbf526667",
                            RoleId = "276af310-41ad-46ca-84b0-90fcfa1833fa"
                        },
                        new
                        {
                            UserId = "ecb4066f-59c7-41c9-99e6-32e354cd507f",
                            RoleId = "3b5ddb63-bdb1-448d-93ce-6f1475b8316f"
                        },
                        new
                        {
                            UserId = "fbd1a202-e0fe-4a4e-83e4-fd9b2cba7aea",
                            RoleId = "276af310-41ad-46ca-84b0-90fcfa1833fa"
                        },
                        new
                        {
                            UserId = "513f83a8-378e-44c8-9519-24dfa658f140",
                            RoleId = "3b5ddb63-bdb1-448d-93ce-6f1475b8316f"
                        },
                        new
                        {
                            UserId = "e15858e1-975c-4037-a834-191acb802e51",
                            RoleId = "276af310-41ad-46ca-84b0-90fcfa1833fa"
                        },
                        new
                        {
                            UserId = "75f0ab6f-1706-492a-9c73-247a84822fb2",
                            RoleId = "276af310-41ad-46ca-84b0-90fcfa1833fa"
                        },
                        new
                        {
                            UserId = "967760ee-6c1f-458e-a844-acb7b95fef4c",
                            RoleId = "3b5ddb63-bdb1-448d-93ce-6f1475b8316f"
                        },
                        new
                        {
                            UserId = "265bbb85-edfc-4c43-af1f-5e09164c732f",
                            RoleId = "276af310-41ad-46ca-84b0-90fcfa1833fa"
                        },
                        new
                        {
                            UserId = "8829499e-b67e-425f-bda0-6b9964a759da",
                            RoleId = "3b5ddb63-bdb1-448d-93ce-6f1475b8316f"
                        },
                        new
                        {
                            UserId = "b264f183-8818-4e65-85b4-bc040204aa7b",
                            RoleId = "276af310-41ad-46ca-84b0-90fcfa1833fa"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Domain.Models.RefreshToken", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
