// <auto-generated />
using System;
using Infrastructure.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Domain.Models.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Price")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = new Guid("1e2540e6-c911-4767-ae3b-1d06c8d2bd96"),
                            Description = "New ABC 13 9370, 13.3, 5th Gen CoreA5-8250U, 8GB RAM, 256GB SSD, power UHD Graphics, OS 10 Home, OS Office A & J 2016",
                            Name = "Awesome Concrete Ball",
                            Price = "245.04"
                        },
                        new
                        {
                            Id = new Guid("98987ba0-e989-46fc-840a-b7618176000e"),
                            Description = "Andy shoes are designed to keeping in mind durability as well as trends, the most stylish range of shoes & sandals",
                            Name = "Generic Granite Pants",
                            Price = "843.60"
                        },
                        new
                        {
                            Id = new Guid("b5387356-d2b3-423b-8e31-a31d58c47dfb"),
                            Description = "Boston's most advanced compression wear technology increases muscle oxygenation, stabilizes active muscles",
                            Name = "Rustic Soft Gloves",
                            Price = "43.46"
                        },
                        new
                        {
                            Id = new Guid("90793e79-0025-473b-9731-78e0771cd8b5"),
                            Description = "Ergonomic executive chair upholstered in bonded black leather and PVC padded seat and back for all-day comfort and support",
                            Name = "Tasty Fresh Pizza",
                            Price = "922.90"
                        },
                        new
                        {
                            Id = new Guid("675736ea-6bd4-4195-b2db-1467ac734ccf"),
                            Description = "Ergonomic executive chair upholstered in bonded black leather and PVC padded seat and back for all-day comfort and support",
                            Name = "Practical Granite Shoes",
                            Price = "678.17"
                        },
                        new
                        {
                            Id = new Guid("3320c00d-5c2d-4862-b89d-60ae0a0dabf2"),
                            Description = "Andy shoes are designed to keeping in mind durability as well as trends, the most stylish range of shoes & sandals",
                            Name = "Incredible Steel Ball",
                            Price = "569.96"
                        },
                        new
                        {
                            Id = new Guid("9e34a7ee-ed4b-4bd0-b9fe-d179bcd9205d"),
                            Description = "The Football Is Good For Training And Recreational Purposes",
                            Name = "Ergonomic Rubber Soap",
                            Price = "343.87"
                        },
                        new
                        {
                            Id = new Guid("b8af4e29-1134-4675-84b9-56d14942a536"),
                            Description = "Ergonomic executive chair upholstered in bonded black leather and PVC padded seat and back for all-day comfort and support",
                            Name = "Generic Concrete Hat",
                            Price = "257.16"
                        },
                        new
                        {
                            Id = new Guid("c3040eb4-6b15-4e7a-ba0b-311592f1e3ea"),
                            Description = "Andy shoes are designed to keeping in mind durability as well as trends, the most stylish range of shoes & sandals",
                            Name = "Sleek Rubber Pizza",
                            Price = "960.37"
                        },
                        new
                        {
                            Id = new Guid("7a040d62-fd72-42bc-8a24-486b0008c448"),
                            Description = "The Nagasaki Lander is the trademarked name of several series of Nagasaki sport bikes, that started with the 1984 ABC800J",
                            Name = "Unbranded Frozen Pants",
                            Price = "639.69"
                        },
                        new
                        {
                            Id = new Guid("f22bf298-5c22-4d85-8b00-1025931a7e9b"),
                            Description = "The Apollotech B340 is an affordable wireless mouse with reliable connectivity, 12 months battery life and modern design",
                            Name = "Intelligent Cotton Bike",
                            Price = "609.48"
                        },
                        new
                        {
                            Id = new Guid("c87d2f64-8dba-44dd-8bf6-b814b4c79fbc"),
                            Description = "Ergonomic executive chair upholstered in bonded black leather and PVC padded seat and back for all-day comfort and support",
                            Name = "Fantastic Soft Chicken",
                            Price = "378.33"
                        },
                        new
                        {
                            Id = new Guid("2940255a-bc75-469f-847b-a242d8e6520c"),
                            Description = "Carbonite web goalkeeper gloves are ergonomically designed to give easy fit",
                            Name = "Incredible Cotton Shirt",
                            Price = "916.10"
                        },
                        new
                        {
                            Id = new Guid("4a7c1335-32b3-44ee-9de4-4f13b79a92c4"),
                            Description = "The Apollotech B340 is an affordable wireless mouse with reliable connectivity, 12 months battery life and modern design",
                            Name = "Fantastic Metal Bacon",
                            Price = "237.41"
                        },
                        new
                        {
                            Id = new Guid("0239803c-36be-4762-9b5f-846804e6649a"),
                            Description = "New ABC 13 9370, 13.3, 5th Gen CoreA5-8250U, 8GB RAM, 256GB SSD, power UHD Graphics, OS 10 Home, OS Office A & J 2016",
                            Name = "Refined Soft Ball",
                            Price = "945.29"
                        },
                        new
                        {
                            Id = new Guid("e281ebcc-53f3-46f7-8efd-896c57ad3b2e"),
                            Description = "The slim & simple Maple Gaming Keyboard from Dev Byte comes with a sleek body and 7- Color RGB LED Back-lighting for smart functionality",
                            Name = "Licensed Concrete Soap",
                            Price = "113.02"
                        },
                        new
                        {
                            Id = new Guid("3a209c4d-bb6b-4756-8add-f61ca3a80c24"),
                            Description = "New ABC 13 9370, 13.3, 5th Gen CoreA5-8250U, 8GB RAM, 256GB SSD, power UHD Graphics, OS 10 Home, OS Office A & J 2016",
                            Name = "Tasty Wooden Salad",
                            Price = "559.15"
                        },
                        new
                        {
                            Id = new Guid("db65688b-ed18-4307-8cf9-b831ffe368f7"),
                            Description = "The slim & simple Maple Gaming Keyboard from Dev Byte comes with a sleek body and 7- Color RGB LED Back-lighting for smart functionality",
                            Name = "Licensed Metal Sausages",
                            Price = "525.82"
                        },
                        new
                        {
                            Id = new Guid("99dbbb4f-6f7c-4e2b-8917-c033c47dbb52"),
                            Description = "Ergonomic executive chair upholstered in bonded black leather and PVC padded seat and back for all-day comfort and support",
                            Name = "Unbranded Cotton Chicken",
                            Price = "593.10"
                        },
                        new
                        {
                            Id = new Guid("e2bf7cf5-565f-4bf8-8104-d41ffee99165"),
                            Description = "New ABC 13 9370, 13.3, 5th Gen CoreA5-8250U, 8GB RAM, 256GB SSD, power UHD Graphics, OS 10 Home, OS Office A & J 2016",
                            Name = "Intelligent Concrete Soap",
                            Price = "385.96"
                        },
                        new
                        {
                            Id = new Guid("9f6c72c9-e00d-4651-bcdb-34d09ce4c580"),
                            Description = "New ABC 13 9370, 13.3, 5th Gen CoreA5-8250U, 8GB RAM, 256GB SSD, power UHD Graphics, OS 10 Home, OS Office A & J 2016",
                            Name = "Gorgeous Cotton Ball",
                            Price = "22.42"
                        },
                        new
                        {
                            Id = new Guid("5008e6c4-08fe-4105-ad6c-380b7b109352"),
                            Description = "Boston's most advanced compression wear technology increases muscle oxygenation, stabilizes active muscles",
                            Name = "Small Concrete Gloves",
                            Price = "42.59"
                        },
                        new
                        {
                            Id = new Guid("2babd95e-94f7-4e49-b8d1-9a229543f8e8"),
                            Description = "Andy shoes are designed to keeping in mind durability as well as trends, the most stylish range of shoes & sandals",
                            Name = "Awesome Steel Fish",
                            Price = "570.29"
                        },
                        new
                        {
                            Id = new Guid("3e664a6b-d907-4542-9864-5fd54d79421f"),
                            Description = "The Nagasaki Lander is the trademarked name of several series of Nagasaki sport bikes, that started with the 1984 ABC800J",
                            Name = "Refined Concrete Table",
                            Price = "356.83"
                        },
                        new
                        {
                            Id = new Guid("3868afe1-27d2-4048-9f37-6afe88826059"),
                            Description = "The beautiful range of Apple Naturalé that has an exciting mix of natural ingredients. With the Goodness of 100% Natural Ingredients",
                            Name = "Fantastic Fresh Salad",
                            Price = "182.67"
                        },
                        new
                        {
                            Id = new Guid("29f27ff1-7ab7-4496-8567-7aa0eade9a3b"),
                            Description = "The Nagasaki Lander is the trademarked name of several series of Nagasaki sport bikes, that started with the 1984 ABC800J",
                            Name = "Intelligent Frozen Sausages",
                            Price = "840.27"
                        },
                        new
                        {
                            Id = new Guid("0136faaf-fb0f-4ae0-ba5b-08d92b912b29"),
                            Description = "The Nagasaki Lander is the trademarked name of several series of Nagasaki sport bikes, that started with the 1984 ABC800J",
                            Name = "Gorgeous Plastic Chair",
                            Price = "217.05"
                        },
                        new
                        {
                            Id = new Guid("2477ced6-d2ff-44d4-b925-c743016d3950"),
                            Description = "The beautiful range of Apple Naturalé that has an exciting mix of natural ingredients. With the Goodness of 100% Natural Ingredients",
                            Name = "Small Cotton Pants",
                            Price = "5.87"
                        },
                        new
                        {
                            Id = new Guid("426c06e3-0e7b-4c68-b344-4358ad7ddc7c"),
                            Description = "The slim & simple Maple Gaming Keyboard from Dev Byte comes with a sleek body and 7- Color RGB LED Back-lighting for smart functionality",
                            Name = "Handcrafted Plastic Ball",
                            Price = "17.59"
                        },
                        new
                        {
                            Id = new Guid("2c8d10a4-6fab-4d51-b20a-a902f0582536"),
                            Description = "The Football Is Good For Training And Recreational Purposes",
                            Name = "Sleek Plastic Bike",
                            Price = "890.78"
                        },
                        new
                        {
                            Id = new Guid("c177f10b-f46b-47d9-ae1c-8fd8df8f2013"),
                            Description = "Ergonomic executive chair upholstered in bonded black leather and PVC padded seat and back for all-day comfort and support",
                            Name = "Incredible Metal Sausages",
                            Price = "864.62"
                        },
                        new
                        {
                            Id = new Guid("aacb5499-7f95-4904-b6de-668489951bac"),
                            Description = "The Nagasaki Lander is the trademarked name of several series of Nagasaki sport bikes, that started with the 1984 ABC800J",
                            Name = "Rustic Plastic Gloves",
                            Price = "795.25"
                        },
                        new
                        {
                            Id = new Guid("17f833e8-bab6-428e-8dec-7ae5c92db61d"),
                            Description = "Andy shoes are designed to keeping in mind durability as well as trends, the most stylish range of shoes & sandals",
                            Name = "Handcrafted Granite Cheese",
                            Price = "495.39"
                        },
                        new
                        {
                            Id = new Guid("da753bb9-4ae5-471b-858b-78ee603f1f19"),
                            Description = "The slim & simple Maple Gaming Keyboard from Dev Byte comes with a sleek body and 7- Color RGB LED Back-lighting for smart functionality",
                            Name = "Handmade Frozen Fish",
                            Price = "21.59"
                        },
                        new
                        {
                            Id = new Guid("58176b2d-8609-4183-a816-42f99a4267b7"),
                            Description = "The Apollotech B340 is an affordable wireless mouse with reliable connectivity, 12 months battery life and modern design",
                            Name = "Incredible Rubber Chair",
                            Price = "237.65"
                        },
                        new
                        {
                            Id = new Guid("f2b696ef-a9ba-4ff6-914a-f1d32d753f88"),
                            Description = "The Football Is Good For Training And Recreational Purposes",
                            Name = "Gorgeous Rubber Pants",
                            Price = "686.93"
                        },
                        new
                        {
                            Id = new Guid("41f5b6ae-1ed1-4d7f-b120-6d0ba35f3362"),
                            Description = "New range of formal shirts are designed keeping you in mind. With fits and styling that will make you stand apart",
                            Name = "Ergonomic Granite Computer",
                            Price = "357.06"
                        },
                        new
                        {
                            Id = new Guid("ccfc72e6-f2a3-47e3-affb-d8a59c02892e"),
                            Description = "Carbonite web goalkeeper gloves are ergonomically designed to give easy fit",
                            Name = "Incredible Frozen Chicken",
                            Price = "255.66"
                        },
                        new
                        {
                            Id = new Guid("31000e82-a919-4baa-b999-d23801c4c1bc"),
                            Description = "Boston's most advanced compression wear technology increases muscle oxygenation, stabilizes active muscles",
                            Name = "Handcrafted Plastic Fish",
                            Price = "715.45"
                        },
                        new
                        {
                            Id = new Guid("2d93381e-3a26-425f-9cf8-e076f691f3ba"),
                            Description = "The Football Is Good For Training And Recreational Purposes",
                            Name = "Incredible Steel Shirt",
                            Price = "61.42"
                        },
                        new
                        {
                            Id = new Guid("d17b3e02-c1ff-43fd-972d-11bbcea746ae"),
                            Description = "Andy shoes are designed to keeping in mind durability as well as trends, the most stylish range of shoes & sandals",
                            Name = "Handmade Granite Fish",
                            Price = "942.19"
                        },
                        new
                        {
                            Id = new Guid("fcd467ad-e57f-4cf5-9f68-c70c3301d20e"),
                            Description = "Carbonite web goalkeeper gloves are ergonomically designed to give easy fit",
                            Name = "Practical Steel Chips",
                            Price = "235.16"
                        },
                        new
                        {
                            Id = new Guid("30379c44-af1e-4f99-8c30-3c9dcb287bde"),
                            Description = "New range of formal shirts are designed keeping you in mind. With fits and styling that will make you stand apart",
                            Name = "Handcrafted Metal Chips",
                            Price = "856.82"
                        },
                        new
                        {
                            Id = new Guid("6e66e59d-8776-427d-a7c0-2c73bec2e85a"),
                            Description = "Ergonomic executive chair upholstered in bonded black leather and PVC padded seat and back for all-day comfort and support",
                            Name = "Intelligent Soft Tuna",
                            Price = "981.70"
                        },
                        new
                        {
                            Id = new Guid("d29ca191-83a4-4dbd-b26f-a1696e388b72"),
                            Description = "The slim & simple Maple Gaming Keyboard from Dev Byte comes with a sleek body and 7- Color RGB LED Back-lighting for smart functionality",
                            Name = "Handcrafted Plastic Sausages",
                            Price = "691.38"
                        },
                        new
                        {
                            Id = new Guid("bb6725be-2875-4b2d-b795-f0cdb9fe2b02"),
                            Description = "Carbonite web goalkeeper gloves are ergonomically designed to give easy fit",
                            Name = "Handcrafted Fresh Hat",
                            Price = "277.24"
                        },
                        new
                        {
                            Id = new Guid("dda4e4de-c2df-4f25-b53f-0abc283f4df9"),
                            Description = "The beautiful range of Apple Naturalé that has an exciting mix of natural ingredients. With the Goodness of 100% Natural Ingredients",
                            Name = "Awesome Steel Shoes",
                            Price = "167.00"
                        },
                        new
                        {
                            Id = new Guid("d4ec0a6c-1c76-4369-bd4b-26547f1fa3db"),
                            Description = "The Football Is Good For Training And Recreational Purposes",
                            Name = "Generic Granite Soap",
                            Price = "613.30"
                        },
                        new
                        {
                            Id = new Guid("254caab5-1251-428d-9a0b-58b4f3109b27"),
                            Description = "Boston's most advanced compression wear technology increases muscle oxygenation, stabilizes active muscles",
                            Name = "Intelligent Metal Bacon",
                            Price = "250.93"
                        },
                        new
                        {
                            Id = new Guid("431c496d-7af3-4490-bc64-75b3367e921b"),
                            Description = "The Nagasaki Lander is the trademarked name of several series of Nagasaki sport bikes, that started with the 1984 ABC800J",
                            Name = "Unbranded Granite Shoes",
                            Price = "597.43"
                        },
                        new
                        {
                            Id = new Guid("00288689-8dcc-47e7-a8c2-f17109875b80"),
                            Description = "Andy shoes are designed to keeping in mind durability as well as trends, the most stylish range of shoes & sandals",
                            Name = "Awesome Cotton Salad",
                            Price = "775.21"
                        },
                        new
                        {
                            Id = new Guid("5a8497cc-59f5-4b3c-bfa0-a318ea753868"),
                            Description = "The Football Is Good For Training And Recreational Purposes",
                            Name = "Practical Cotton Bike",
                            Price = "403.82"
                        },
                        new
                        {
                            Id = new Guid("07d984da-9e9b-4c90-8177-27709cdd7a27"),
                            Description = "The Nagasaki Lander is the trademarked name of several series of Nagasaki sport bikes, that started with the 1984 ABC800J",
                            Name = "Licensed Soft Chicken",
                            Price = "363.79"
                        },
                        new
                        {
                            Id = new Guid("9efec2df-e4b2-4d41-9354-b4459092e3ae"),
                            Description = "The Apollotech B340 is an affordable wireless mouse with reliable connectivity, 12 months battery life and modern design",
                            Name = "Practical Plastic Car",
                            Price = "158.98"
                        },
                        new
                        {
                            Id = new Guid("b7d7dead-f3b8-473e-9807-aaa4cc796689"),
                            Description = "The beautiful range of Apple Naturalé that has an exciting mix of natural ingredients. With the Goodness of 100% Natural Ingredients",
                            Name = "Awesome Concrete Mouse",
                            Price = "482.45"
                        },
                        new
                        {
                            Id = new Guid("5ba53bba-c9d8-40b3-93f2-f9e0caa7da58"),
                            Description = "Boston's most advanced compression wear technology increases muscle oxygenation, stabilizes active muscles",
                            Name = "Fantastic Plastic Pizza",
                            Price = "262.51"
                        },
                        new
                        {
                            Id = new Guid("adbc8905-90d0-4603-9269-f1df87942ef0"),
                            Description = "Ergonomic executive chair upholstered in bonded black leather and PVC padded seat and back for all-day comfort and support",
                            Name = "Small Concrete Table",
                            Price = "888.53"
                        },
                        new
                        {
                            Id = new Guid("91f08a4c-cbb5-4955-a58a-6bacd98c8b5c"),
                            Description = "Carbonite web goalkeeper gloves are ergonomically designed to give easy fit",
                            Name = "Intelligent Steel Bacon",
                            Price = "265.41"
                        },
                        new
                        {
                            Id = new Guid("11cb5fdc-f2b4-45d6-83e8-86e1e0336ef8"),
                            Description = "Carbonite web goalkeeper gloves are ergonomically designed to give easy fit",
                            Name = "Small Frozen Chair",
                            Price = "228.21"
                        },
                        new
                        {
                            Id = new Guid("209e6e98-7f48-4cd3-b2b0-62b26e8fb744"),
                            Description = "The Apollotech B340 is an affordable wireless mouse with reliable connectivity, 12 months battery life and modern design",
                            Name = "Small Steel Chips",
                            Price = "609.42"
                        },
                        new
                        {
                            Id = new Guid("f0820faa-93fc-4971-b017-8aed0afedb2c"),
                            Description = "New ABC 13 9370, 13.3, 5th Gen CoreA5-8250U, 8GB RAM, 256GB SSD, power UHD Graphics, OS 10 Home, OS Office A & J 2016",
                            Name = "Ergonomic Granite Bacon",
                            Price = "602.41"
                        },
                        new
                        {
                            Id = new Guid("67fe225d-2c49-40fd-8ca0-d59a4058398b"),
                            Description = "Boston's most advanced compression wear technology increases muscle oxygenation, stabilizes active muscles",
                            Name = "Small Steel Towels",
                            Price = "179.42"
                        },
                        new
                        {
                            Id = new Guid("3384cf42-22d2-4341-8751-1eb07d624364"),
                            Description = "The Apollotech B340 is an affordable wireless mouse with reliable connectivity, 12 months battery life and modern design",
                            Name = "Ergonomic Fresh Sausages",
                            Price = "621.12"
                        },
                        new
                        {
                            Id = new Guid("137bcfa8-d198-42a1-80ee-d8e6082dcd12"),
                            Description = "The Nagasaki Lander is the trademarked name of several series of Nagasaki sport bikes, that started with the 1984 ABC800J",
                            Name = "Generic Fresh Chips",
                            Price = "655.63"
                        },
                        new
                        {
                            Id = new Guid("32329b47-d873-4aa6-88d1-904f0b7e8006"),
                            Description = "The slim & simple Maple Gaming Keyboard from Dev Byte comes with a sleek body and 7- Color RGB LED Back-lighting for smart functionality",
                            Name = "Ergonomic Steel Computer",
                            Price = "731.07"
                        },
                        new
                        {
                            Id = new Guid("ed80289b-7f7e-4108-8904-7a1e07deb4ff"),
                            Description = "New range of formal shirts are designed keeping you in mind. With fits and styling that will make you stand apart",
                            Name = "Fantastic Soft Soap",
                            Price = "887.15"
                        },
                        new
                        {
                            Id = new Guid("c8ef7f21-b998-4942-8ee7-f1a8cbeaa6b7"),
                            Description = "Ergonomic executive chair upholstered in bonded black leather and PVC padded seat and back for all-day comfort and support",
                            Name = "Tasty Cotton Fish",
                            Price = "175.15"
                        },
                        new
                        {
                            Id = new Guid("905ba7d1-f34a-457b-ad95-f2e445c29cb2"),
                            Description = "The Football Is Good For Training And Recreational Purposes",
                            Name = "Unbranded Wooden Car",
                            Price = "785.76"
                        });
                });

            modelBuilder.Entity("Domain.Models.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ExpiryDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsRevoked")
                        .HasColumnType("bit");

                    b.Property<bool>("IsUsed")
                        .HasColumnType("bit");

                    b.Property<string>("JwtId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "e4528b8b-97e0-4cb9-b268-5bdabfff4804",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "69e13cf6-7d39-42a9-89b7-0e9be4c33092",
                            Email = "Maurice_Cartwright@yahoo.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "Maurice_Cartwright@yahoo.com",
                            NormalizedUserName = "Maurice13",
                            PasswordHash = "AQAAAAIAAYagAAAAEGkZ5pLJ38QeXFx51nr2I9vP49jteB2mjBAGU84t9zSF7Tn/JtZNT4lC1VAnRq4LvQ==",
                            PhoneNumber = "236.216.4782 x78080",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "20f95873-c6ee-457d-87f6-f91cecc31a7f",
                            TwoFactorEnabled = false,
                            UserName = "Maurice13"
                        },
                        new
                        {
                            Id = "10a31915-4406-4dc5-b21f-0e9cf4c9b852",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "4f408abe-fca6-422f-9795-71ee9673e715",
                            Email = "Ella_Kshlerin75@hotmail.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedEmail = "Ella_Kshlerin75@hotmail.com",
                            NormalizedUserName = "Ella54",
                            PasswordHash = "AQAAAAIAAYagAAAAEItEB9TM1Cn2/5eS/jCiOs39Mm4ZqwX6sEEMcQQ1NsGunuHWcvdGvTXYlLaBSGUfgw==",
                            PhoneNumber = "687.608.0934",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "f72378b9-3dba-411d-a528-97b9ea93111c",
                            TwoFactorEnabled = false,
                            UserName = "Ella54"
                        },
                        new
                        {
                            Id = "05ffd985-95e1-4232-b3ca-60465abf8fdc",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "2b8756ef-728f-4f7c-853b-50dc4a694abd",
                            Email = "Kelvin.VonRueden@hotmail.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "Kelvin.VonRueden@hotmail.com",
                            NormalizedUserName = "Kelvin_VonRueden61",
                            PasswordHash = "AQAAAAIAAYagAAAAEH2M+DYDRxHbxU2jiPAed/naGF0n0ac7na7V18WnUUXpRQBB0MhUkAZBZ2e8+e2ezg==",
                            PhoneNumber = "514.537.5226 x079",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "3a84549d-617a-4e03-a28a-d27a984bc886",
                            TwoFactorEnabled = false,
                            UserName = "Kelvin_VonRueden61"
                        },
                        new
                        {
                            Id = "611636f8-add1-4133-92b0-e4bc35f6ccfd",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "72fe023d-a551-4e59-b0ec-c86be53e44f1",
                            Email = "Betty.King@yahoo.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "Betty.King@yahoo.com",
                            NormalizedUserName = "Betty6",
                            PasswordHash = "AQAAAAIAAYagAAAAEHT86xciAKEO0TZxsoYJuypQkfAuZNOCUAjotTaH89yIQdMyTLOvYuASKx03IZ9qvg==",
                            PhoneNumber = "(832) 762-2620",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "d5489c64-1ac8-4b12-ac68-ed7a0b2327ee",
                            TwoFactorEnabled = false,
                            UserName = "Betty6"
                        },
                        new
                        {
                            Id = "14339328-0695-41ea-8fda-d31f4e855ccd",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "58e11ef2-530f-4bf7-bd23-5244de13e759",
                            Email = "Margie97@hotmail.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedEmail = "Margie97@hotmail.com",
                            NormalizedUserName = "Margie.Carter",
                            PasswordHash = "AQAAAAIAAYagAAAAEC8wZiaynLPjD+3Of+klfCpbLc/q09+6pv5jHF5xw8WKSrVgqURpSqlQ5bN11dSX/Q==",
                            PhoneNumber = "308-526-7833 x209",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "49aa9959-989c-4820-955d-c276d9f6c1b9",
                            TwoFactorEnabled = false,
                            UserName = "Margie.Carter"
                        },
                        new
                        {
                            Id = "05f06db7-c3ad-484c-9b42-3a1bdf50260d",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "d847b5bb-52ce-43fb-a3f4-564a75a6ae31",
                            Email = "Ismael_Gusikowski@gmail.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedEmail = "Ismael_Gusikowski@gmail.com",
                            NormalizedUserName = "Ismael_Gusikowski",
                            PasswordHash = "AQAAAAIAAYagAAAAELEob31WCdD/mcoNk6FnwfXYne/g7qRgbxeHrvtVPcKAo7PFEWfZe8F5QFp7nTMABg==",
                            PhoneNumber = "995.352.6888",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "5c105aa5-c321-42c0-9782-d7a549f74752",
                            TwoFactorEnabled = false,
                            UserName = "Ismael_Gusikowski"
                        },
                        new
                        {
                            Id = "d146992f-82be-446d-95af-6d46332855ac",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "4ca31e64-5612-4ead-96d0-0a6310907d44",
                            Email = "Faith.Schmeler48@hotmail.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "Faith.Schmeler48@hotmail.com",
                            NormalizedUserName = "Faith_Schmeler",
                            PasswordHash = "AQAAAAIAAYagAAAAEF9kQltzrYQXpG0LduHVpEDJk2pF5WZTnKkNral7NxRnNkBJJ24smmDcoAeIDPpchQ==",
                            PhoneNumber = "(908) 496-8330",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "112a7757-8543-4b46-9e79-24f36531bd97",
                            TwoFactorEnabled = false,
                            UserName = "Faith_Schmeler"
                        },
                        new
                        {
                            Id = "03a1bfc6-bd7b-4823-9117-9caec23cba6b",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "ef16d9b7-4a42-4db5-a312-66e3eecaab88",
                            Email = "Blake_Weimann61@gmail.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "Blake_Weimann61@gmail.com",
                            NormalizedUserName = "Blake13",
                            PasswordHash = "AQAAAAIAAYagAAAAEDm3ruTSeZEho6HUy2WU3VTOwEMPBBkp32FFGgDjd/f/c/Fbwm4j0PUVBJbiAvEBHw==",
                            PhoneNumber = "1-415-344-4434",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "77a7056a-65d5-4501-a787-28f4717f4ec5",
                            TwoFactorEnabled = false,
                            UserName = "Blake13"
                        },
                        new
                        {
                            Id = "f11d8862-6aff-4903-b577-a9f5d0a131eb",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "27ae9273-e975-47f7-b3c3-cbf03e4ce4b2",
                            Email = "Angie.Senger15@hotmail.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "Angie.Senger15@hotmail.com",
                            NormalizedUserName = "Angie50",
                            PasswordHash = "AQAAAAIAAYagAAAAEOTFpCfCncZzCvvun+5D+uOSSyaXdLeKKC6mYppt3qg9UfWTIssuZvWQPDTHHhextg==",
                            PhoneNumber = "(611) 382-2234",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "ac91dfec-d374-443d-baf5-266076c7b9ad",
                            TwoFactorEnabled = false,
                            UserName = "Angie50"
                        },
                        new
                        {
                            Id = "72ab5ed5-d3d8-48cf-8428-b32cab3d4f66",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "604dcb0f-7303-4d84-a27b-29bf2ea959c2",
                            Email = "Derek7@hotmail.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedEmail = "Derek7@hotmail.com",
                            NormalizedUserName = "Derek56",
                            PasswordHash = "AQAAAAIAAYagAAAAEH0CYk2AXCpRHJ+HDuAU5GC9b3UcTWybna0R1BzFSC/3Ua/Gdw/xf/6IYlSI0he29w==",
                            PhoneNumber = "720.527.9708",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "becdd5f9-3f9e-459b-bac2-01fc5003099c",
                            TwoFactorEnabled = false,
                            UserName = "Derek56"
                        },
                        new
                        {
                            Id = "a345a4d0-11eb-4f8e-b683-d9e447953baa",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "3fd71b49-d90b-49f4-8f42-8ae15063030b",
                            Email = "Scott_Roob29@yahoo.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedEmail = "Scott_Roob29@yahoo.com",
                            NormalizedUserName = "Scott.Roob77",
                            PasswordHash = "AQAAAAIAAYagAAAAECH5ROybdXgOV3b9QR4HMQmB4jPXQjZ0KmbxZOsmBZMVpvNdn+JdFW8yFBhnveFtww==",
                            PhoneNumber = "(712) 480-1725 x64900",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "4435bf8e-04c4-423d-923c-e9f7ffc5c62f",
                            TwoFactorEnabled = false,
                            UserName = "Scott.Roob77"
                        },
                        new
                        {
                            Id = "d886862a-aba2-43ae-908d-9bce3be4e1f7",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "4605690d-9a0c-430b-a5c3-279a4816e9a0",
                            Email = "Vernon_Buckridge78@gmail.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "Vernon_Buckridge78@gmail.com",
                            NormalizedUserName = "Vernon18",
                            PasswordHash = "AQAAAAIAAYagAAAAEOeT7X3biKkh4/uywMonkL6zJl8hgh+oHpiudoyWF9MHwScWi4K8AEOKch0ouTIywA==",
                            PhoneNumber = "909.373.2191",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "0aa995d3-f9b5-4113-8633-7d0bdfdf3b95",
                            TwoFactorEnabled = false,
                            UserName = "Vernon18"
                        },
                        new
                        {
                            Id = "aab58fcc-3f3b-4c93-91f3-d9cc5ec96d68",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "888ea8f3-8cf0-45ba-af9d-da855878888e",
                            Email = "Olivia_Volkman82@gmail.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "Olivia_Volkman82@gmail.com",
                            NormalizedUserName = "Olivia_Volkman",
                            PasswordHash = "AQAAAAIAAYagAAAAEIiw+QFfCfusRPFI7IaefFW+E34bq5BIb9XxmZP3s/4M1ZxbEqpoS9QA9s2AvkxIXw==",
                            PhoneNumber = "1-301-368-8417 x7631",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "c5f7fc44-23c5-41cf-98c8-f514a7e12a61",
                            TwoFactorEnabled = false,
                            UserName = "Olivia_Volkman"
                        },
                        new
                        {
                            Id = "b03ef1cb-25e8-44a6-b942-ece889e02dc8",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "d86437dd-4a65-493f-906a-1b241bac7d80",
                            Email = "Toby66@yahoo.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "Toby66@yahoo.com",
                            NormalizedUserName = "Toby.Marks69",
                            PasswordHash = "AQAAAAIAAYagAAAAEEcl64Z9VfbKXp7lLqsnhNOvctIEzEXNaPVKi0XhKPac0zSl8/QaKcWBo9mhslFBAQ==",
                            PhoneNumber = "788.720.1382 x1502",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "55e40843-5e26-4365-80e4-c7437fca3d25",
                            TwoFactorEnabled = false,
                            UserName = "Toby.Marks69"
                        },
                        new
                        {
                            Id = "d2927b69-2815-4c0f-bb78-bf07c9507895",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "28cc2c1a-1dc5-4c7c-8890-86943e96a15d",
                            Email = "Erica87@gmail.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedEmail = "Erica87@gmail.com",
                            NormalizedUserName = "Erica31",
                            PasswordHash = "AQAAAAIAAYagAAAAEKyUpnmSqzZXaWRiogWynxpTEu6qylIGEcOTvhuU1XRf6pFmDwLI4rwZAojZg2JhUw==",
                            PhoneNumber = "1-836-887-2464",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "c69c0fde-f8a6-471f-ae55-7e70d85bc537",
                            TwoFactorEnabled = false,
                            UserName = "Erica31"
                        },
                        new
                        {
                            Id = "42d4da42-9ba3-4113-bcfd-f3f5d8d26798",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "cf7a3a99-36cd-4f74-9598-e53bd301dd79",
                            Email = "Betsy22@yahoo.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedEmail = "Betsy22@yahoo.com",
                            NormalizedUserName = "Betsy_Bartoletti97",
                            PasswordHash = "AQAAAAIAAYagAAAAEOMK0yGvI3rdIlQJqNB/khQR0GwRn7HMWr1+KyFBqye+/t8AHCMiFHocg1puWp8RmA==",
                            PhoneNumber = "1-911-366-1177",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "2b20e3a5-ffca-426c-afc0-9f60aa55f4ba",
                            TwoFactorEnabled = false,
                            UserName = "Betsy_Bartoletti97"
                        },
                        new
                        {
                            Id = "5183f5dc-e970-439c-abc7-2296b6a38f48",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "f68e4760-ebc9-4c7c-bc3c-fd8147045d11",
                            Email = "Sophia.Ebert42@gmail.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "Sophia.Ebert42@gmail.com",
                            NormalizedUserName = "Sophia.Ebert56",
                            PasswordHash = "AQAAAAIAAYagAAAAEK9Ham7tUVNL1N6PZnruv19YvAV2dCy18N8TQIyT749uCUXqfNad5U/gvccXOd+FaA==",
                            PhoneNumber = "777-258-5989 x919",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "383b534d-f9f6-4085-8718-7485a3c466a3",
                            TwoFactorEnabled = false,
                            UserName = "Sophia.Ebert56"
                        },
                        new
                        {
                            Id = "2f95c2a8-f440-4b3c-9112-88493f4cee49",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "090562d1-c4ab-4fba-92a7-349d16ad0496",
                            Email = "Mildred71@hotmail.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedEmail = "Mildred71@hotmail.com",
                            NormalizedUserName = "Mildred_Bailey93",
                            PasswordHash = "AQAAAAIAAYagAAAAEF0B8CyeHnYsmOd50wIVYRwGzoTdMZ/JhhbbdfzxPMzF/eQG5vxJKBSxadFjWqw/hg==",
                            PhoneNumber = "1-557-260-8962",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "fac8a84b-28da-412b-b815-254d918cb50e",
                            TwoFactorEnabled = false,
                            UserName = "Mildred_Bailey93"
                        },
                        new
                        {
                            Id = "5f91adb2-fc19-42ba-8b7d-c3a1ec3a4130",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "41698ed7-45c1-4425-b9dc-d89db4661c0d",
                            Email = "Bridget_Wisozk@yahoo.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedEmail = "Bridget_Wisozk@yahoo.com",
                            NormalizedUserName = "Bridget.Wisozk16",
                            PasswordHash = "AQAAAAIAAYagAAAAEEpYntgLI0xCMZMN0aO6bMZeVQ0YkHLvSeZareWU91lAfD7gnwIgAgmssWlhuZcrOg==",
                            PhoneNumber = "361.942.7069 x47993",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "411e7506-256f-4afb-a60b-654a3c7ce3f5",
                            TwoFactorEnabled = false,
                            UserName = "Bridget.Wisozk16"
                        },
                        new
                        {
                            Id = "3fb1f548-ff98-42ce-a05e-40e219334544",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "a24fa89d-4f36-48a9-826f-ff4da4f2d605",
                            Email = "Rogelio.Lynch@yahoo.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "Rogelio.Lynch@yahoo.com",
                            NormalizedUserName = "Rogelio.Lynch17",
                            PasswordHash = "AQAAAAIAAYagAAAAEAn91pAxwInHX45Tfo1mvd8hlAPQTAZJzYMYc26Bj2v5iMptsqGTn5Hk3xY8KBRTHg==",
                            PhoneNumber = "781.364.0493 x77307",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "8d5d9b27-18be-4081-ade3-6451ac43c2e1",
                            TwoFactorEnabled = false,
                            UserName = "Rogelio.Lynch17"
                        },
                        new
                        {
                            Id = "e9ee14ce-026b-4510-bcfa-040553eb1740",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "43520950-baa6-4720-b2ab-413c0835aafa",
                            Email = "Nichole80@hotmail.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "Nichole80@hotmail.com",
                            NormalizedUserName = "Nichole.Marquardt57",
                            PasswordHash = "AQAAAAIAAYagAAAAEH1ZO+GYll71aqV2WtCVow6L3S5QCXm/tmDgs2UhUDAn1fPxl4nsO1Dp0dB5vNi1IA==",
                            PhoneNumber = "(341) 692-8382 x5342",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "d1540d9a-586f-4ba1-b7c8-e062623c6f7f",
                            TwoFactorEnabled = false,
                            UserName = "Nichole.Marquardt57"
                        },
                        new
                        {
                            Id = "23ed0761-991b-4fde-b183-07ac51f2ca4f",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "af1534a0-9f97-43e6-81c6-c62529a49439",
                            Email = "Jeremy.Schultz5@gmail.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedEmail = "Jeremy.Schultz5@gmail.com",
                            NormalizedUserName = "Jeremy_Schultz81",
                            PasswordHash = "AQAAAAIAAYagAAAAEM0wESOQvTKuG40NPLh6KLrUNNCloLLuw2ilGky2/BYhuEIuFWlA/uk4Ur0MAjS+CA==",
                            PhoneNumber = "(273) 453-2679",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "d2058b63-c54d-4648-9f50-64631787e355",
                            TwoFactorEnabled = false,
                            UserName = "Jeremy_Schultz81"
                        },
                        new
                        {
                            Id = "27d733b4-f21c-4bad-9d37-47c5a6f87f24",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "680f503b-78bb-4912-be10-aee69c83c4cf",
                            Email = "Dianne43@hotmail.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "Dianne43@hotmail.com",
                            NormalizedUserName = "Dianne.Hayes87",
                            PasswordHash = "AQAAAAIAAYagAAAAEBNLnWkKwD0Ka0DSzlqXiAbb1kNnWm7r1s7PLUGzLdd02Cq/qrixwdggU6Hfu6hDhw==",
                            PhoneNumber = "747-425-1033 x364",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "f064c666-a8b4-4efd-9a64-3b4709e74677",
                            TwoFactorEnabled = false,
                            UserName = "Dianne.Hayes87"
                        },
                        new
                        {
                            Id = "2207a3ac-0b55-4103-a730-33869ff0f6f9",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "707ae143-96f7-43a3-9c0b-09a3e62c28a6",
                            Email = "Wm83@hotmail.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedEmail = "Wm83@hotmail.com",
                            NormalizedUserName = "Wm53",
                            PasswordHash = "AQAAAAIAAYagAAAAENlaOgmcPvuBcWoVd8HYmJ8AjivL4jYwMgcPr5wAb6qaN3x1TZsbdaIFlXuB7cW+nw==",
                            PhoneNumber = "(482) 729-7418",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "0418e067-5bfc-4f8a-90f0-d662f3cb3d2f",
                            TwoFactorEnabled = false,
                            UserName = "Wm53"
                        },
                        new
                        {
                            Id = "8d9a61ca-a345-483b-a7f8-e767e483ac86",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "ba8cb1ea-1484-477a-ab37-c38ab38a211c",
                            Email = "Susan_Lindgren10@gmail.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "Susan_Lindgren10@gmail.com",
                            NormalizedUserName = "Susan.Lindgren81",
                            PasswordHash = "AQAAAAIAAYagAAAAEE4b5tXtHVg5cizvzRmUWlYgPj/v28gTjeksSjtuxSED8oCOwO7joi/NDZ6PfAvqKQ==",
                            PhoneNumber = "1-588-497-8158",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "38ddb257-6084-410d-938a-5e668bd1099d",
                            TwoFactorEnabled = false,
                            UserName = "Susan.Lindgren81"
                        },
                        new
                        {
                            Id = "c6ca2d95-6b5d-45ff-97b5-cf7ca5b2ff86",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "983b141a-e3df-4c96-89e3-eaa86f08fab2",
                            Email = "Frances.Schumm44@hotmail.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "Frances.Schumm44@hotmail.com",
                            NormalizedUserName = "Frances93",
                            PasswordHash = "AQAAAAIAAYagAAAAEPsSv2OEbtRXYVpMJOmbYUO65U16NBegHK1Hw8HDFqcWOVMrEobcS9s0X1rp6ugS3Q==",
                            PhoneNumber = "246.763.7101",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "67dad906-3717-498d-ba2d-2df4b7ed3510",
                            TwoFactorEnabled = false,
                            UserName = "Frances93"
                        },
                        new
                        {
                            Id = "cf32871a-8423-49f6-93d4-67a2067a9e62",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "7adb504e-2c0e-4d01-8445-b7d71147c7fb",
                            Email = "Marsha_Macejkovic48@hotmail.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "Marsha_Macejkovic48@hotmail.com",
                            NormalizedUserName = "Marsha82",
                            PasswordHash = "AQAAAAIAAYagAAAAEPIX7ICW5MmA5NHLP4z6uVc6RsN7syi8FVuQoDrLf8v43kNSVxdvccVJnurN8y+D3g==",
                            PhoneNumber = "1-365-813-9048",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "f60b3982-9bc6-4ea9-898b-099d59cb1ee9",
                            TwoFactorEnabled = false,
                            UserName = "Marsha82"
                        },
                        new
                        {
                            Id = "0c0f5b42-fcf1-4345-aafe-b424cc45b6c6",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "bdb16ca9-d4db-4c6b-8a08-934d8bc9efd7",
                            Email = "Terrence.Fay54@hotmail.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedEmail = "Terrence.Fay54@hotmail.com",
                            NormalizedUserName = "Terrence80",
                            PasswordHash = "AQAAAAIAAYagAAAAEL5T+wT4Jj7bihNBod8rVOvfG/6elfQErn6rpCzJDO22L2BcApKgPSNkvYD7jHFrjQ==",
                            PhoneNumber = "296-710-1184",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "b9d45c42-de56-4801-9bc5-9f87efd095a7",
                            TwoFactorEnabled = false,
                            UserName = "Terrence80"
                        },
                        new
                        {
                            Id = "39bc388a-16a4-410f-b301-fa97b91b304e",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "73530a09-d630-401c-b94b-89ec55229d08",
                            Email = "Elaine_OReilly57@gmail.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedEmail = "Elaine_OReilly57@gmail.com",
                            NormalizedUserName = "Elaine28",
                            PasswordHash = "AQAAAAIAAYagAAAAEO8mvwSBkTtSIxm0gwQIIqNF8hqqRjEiFdUnj/4zcUXRSWcoFEKx0w85DknROoA1XQ==",
                            PhoneNumber = "762.677.3476",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "52f7757b-73c2-4673-a5b5-e865c48fb6e8",
                            TwoFactorEnabled = false,
                            UserName = "Elaine28"
                        },
                        new
                        {
                            Id = "908092d2-860d-42b7-937b-7a74941d6555",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "b64d1f2b-7163-4a68-9f4b-a1f6eb464659",
                            Email = "Ronald.Mitchell69@hotmail.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "Ronald.Mitchell69@hotmail.com",
                            NormalizedUserName = "Ronald.Mitchell",
                            PasswordHash = "AQAAAAIAAYagAAAAEJytj/PWVi/k5phcR0jo5AgYQp491+Hf4vhmpZl5B9GhxEVlkXrBkz7f2QfSeAakAg==",
                            PhoneNumber = "658-611-5975",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "d241c830-e119-48f1-9b06-2941f8f54c95",
                            TwoFactorEnabled = false,
                            UserName = "Ronald.Mitchell"
                        },
                        new
                        {
                            Id = "4a98b5d5-14a5-44e4-ac2c-d772b7a79d4f",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "b92ebbd3-5594-4fcc-a35a-a13681ca8f5d",
                            Email = "Clyde70@hotmail.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedEmail = "Clyde70@hotmail.com",
                            NormalizedUserName = "Clyde31",
                            PasswordHash = "AQAAAAIAAYagAAAAEBvW7ftANl6ywFehKEnIBzYBvnGjIa7/WgHMDxKd27FmQbIvzfa7vUfVyt+B1WZdDw==",
                            PhoneNumber = "463-424-9921 x673",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "81ea02ad-efbb-4b5f-822b-15a82bcf7829",
                            TwoFactorEnabled = false,
                            UserName = "Clyde31"
                        },
                        new
                        {
                            Id = "999cd408-64bc-4904-b581-392b4ff83d5c",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "c675ef19-35a1-4419-9125-2e73a8394bf4",
                            Email = "Rose.Anderson97@gmail.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "Rose.Anderson97@gmail.com",
                            NormalizedUserName = "Rose.Anderson",
                            PasswordHash = "AQAAAAIAAYagAAAAEABgAkTMO0lnM6H5FHr3pXvQL7C7mY8tOp5ukgoPUmwxIdv3PikbKcgbTJ+/YhH7SQ==",
                            PhoneNumber = "922-596-5238 x1251",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "3b355937-076a-404b-bba9-545f86dc372c",
                            TwoFactorEnabled = false,
                            UserName = "Rose.Anderson"
                        },
                        new
                        {
                            Id = "6d60a968-6907-4d6a-b7de-9c963c740253",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "074fbac8-6345-4aa6-b031-bbedd02bbee4",
                            Email = "Greg_Wintheiser35@gmail.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedEmail = "Greg_Wintheiser35@gmail.com",
                            NormalizedUserName = "Greg_Wintheiser",
                            PasswordHash = "AQAAAAIAAYagAAAAEBU+iiZt3kIjBcsNFLZjYRJ1R5kcZO0odjkZOQoAD20Z0e1vYRFWXPqFW7VMrn/e/w==",
                            PhoneNumber = "1-284-512-0623 x4462",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "972ddfcf-ebfb-4d50-877a-aec6a5f9666c",
                            TwoFactorEnabled = false,
                            UserName = "Greg_Wintheiser"
                        },
                        new
                        {
                            Id = "ecfe73c6-2e9b-433e-a7a8-323d83b67380",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "1916be38-684d-4a27-b396-a2d0ee545bac",
                            Email = "Dwight_Paucek23@gmail.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedEmail = "Dwight_Paucek23@gmail.com",
                            NormalizedUserName = "Dwight.Paucek",
                            PasswordHash = "AQAAAAIAAYagAAAAEIZ3r0lmWD9C+chypFb/D0VRhEuH+2qCnG0LPFJuFkJrwh+XGy71UmOqx+VjIVCG2g==",
                            PhoneNumber = "1-933-725-3050 x438",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "e76a2503-f038-4af4-95f2-fc159326897f",
                            TwoFactorEnabled = false,
                            UserName = "Dwight.Paucek"
                        },
                        new
                        {
                            Id = "e7cb9626-ad36-4753-a881-d1852ff5edcd",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "96ce86bb-bf7a-4776-85f6-71bdb20921dc",
                            Email = "Ruben.Cartwright@yahoo.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedEmail = "Ruben.Cartwright@yahoo.com",
                            NormalizedUserName = "Ruben_Cartwright",
                            PasswordHash = "AQAAAAIAAYagAAAAEBNQDfAw1f/AOIUQijqhHd9CyhJB3tzYCssc8o90BUAVjxHfP9n1Sw3KjJyxQjXKfw==",
                            PhoneNumber = "1-714-524-0391",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "82e6ac06-bc13-4158-90ff-c57c54042bbc",
                            TwoFactorEnabled = false,
                            UserName = "Ruben_Cartwright"
                        },
                        new
                        {
                            Id = "950594c8-e233-4c7a-aea5-533a6be5e40e",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "fcf8f83a-b5b5-4dca-a319-1c5bd9faad9a",
                            Email = "Caroline.Prosacco@yahoo.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedEmail = "Caroline.Prosacco@yahoo.com",
                            NormalizedUserName = "Caroline.Prosacco27",
                            PasswordHash = "AQAAAAIAAYagAAAAEEoWJry1GHDXZjTRb4fbfl+oHqYzkUl3IndX+Ia85nwKU1p4kUeBO6vGfZ4qBGtNGw==",
                            PhoneNumber = "709-429-5131",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "38118647-69d0-4c0b-9274-c0eb970d4f46",
                            TwoFactorEnabled = false,
                            UserName = "Caroline.Prosacco27"
                        },
                        new
                        {
                            Id = "89a2ad18-0054-47c0-aefa-089481dcadd9",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "932f9231-2e24-4e58-93b1-c3212e76f386",
                            Email = "Patty_Parisian@gmail.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedEmail = "Patty_Parisian@gmail.com",
                            NormalizedUserName = "Patty_Parisian30",
                            PasswordHash = "AQAAAAIAAYagAAAAEDG6kcfN9MmQtBVr4ra/GiUK1UAWdsQnv7N5CsJWto3L9gzJrcO/DRl8Dzy2W2VnYQ==",
                            PhoneNumber = "454.597.3834",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "c29bec3e-bb9e-4072-9b2f-2f28d436d283",
                            TwoFactorEnabled = false,
                            UserName = "Patty_Parisian30"
                        },
                        new
                        {
                            Id = "23b71de2-bb4b-4df1-b014-859ade2cf2f0",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "f16f26b8-3f24-4fc0-871d-efde63e09f00",
                            Email = "Chad.Schoen@yahoo.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "Chad.Schoen@yahoo.com",
                            NormalizedUserName = "Chad70",
                            PasswordHash = "AQAAAAIAAYagAAAAED6KLfGezu/Yuq4vN1pYiibXsopZvu3ECYB53aOLlrsymKU92pZgPQvGWf8arvBP0g==",
                            PhoneNumber = "(344) 482-9858 x91193",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "89dc30c6-5179-4128-8756-a47909bec042",
                            TwoFactorEnabled = false,
                            UserName = "Chad70"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Domain.Models.RefreshToken", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
