// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Persistence.Database;

#nullable disable

namespace Persistence.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20221211203425_v1-initial-migration")]
    partial class v1initialmigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Domain.Models.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Price")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = new Guid("9b14fb40-e7aa-4c75-8ee6-9ac56f248a59"),
                            Description = "New range of formal shirts are designed keeping you in mind. With fits and styling that will make you stand apart",
                            Name = "Unbranded Concrete Soap",
                            Price = "903.95"
                        },
                        new
                        {
                            Id = new Guid("5dd714b9-904f-49bc-bbd6-689b14c28808"),
                            Description = "New ABC 13 9370, 13.3, 5th Gen CoreA5-8250U, 8GB RAM, 256GB SSD, power UHD Graphics, OS 10 Home, OS Office A & J 2016",
                            Name = "Awesome Plastic Car",
                            Price = "117.55"
                        },
                        new
                        {
                            Id = new Guid("b62c01ce-98b1-45b8-a021-70bedc6e7789"),
                            Description = "Andy shoes are designed to keeping in mind durability as well as trends, the most stylish range of shoes & sandals",
                            Name = "Unbranded Wooden Table",
                            Price = "207.44"
                        },
                        new
                        {
                            Id = new Guid("bb70e0ab-72b6-4c0f-9fad-a579d6695115"),
                            Description = "The automobile layout consists of a front-engine design, with transaxle-type transmissions mounted at the rear of the engine and four wheel drive",
                            Name = "Fantastic Steel Hat",
                            Price = "20.67"
                        },
                        new
                        {
                            Id = new Guid("89c90a04-9b4b-4fb0-aee3-d77920e1965b"),
                            Description = "Ergonomic executive chair upholstered in bonded black leather and PVC padded seat and back for all-day comfort and support",
                            Name = "Licensed Plastic Chips",
                            Price = "982.45"
                        },
                        new
                        {
                            Id = new Guid("48c2e651-435b-4339-945d-a3489aedd093"),
                            Description = "The Apollotech B340 is an affordable wireless mouse with reliable connectivity, 12 months battery life and modern design",
                            Name = "Licensed Granite Cheese",
                            Price = "575.46"
                        },
                        new
                        {
                            Id = new Guid("18739b05-a6a2-4ebc-b009-7c492ee5a2bc"),
                            Description = "The automobile layout consists of a front-engine design, with transaxle-type transmissions mounted at the rear of the engine and four wheel drive",
                            Name = "Intelligent Fresh Shirt",
                            Price = "685.49"
                        },
                        new
                        {
                            Id = new Guid("e4ff1c8b-8448-406c-aaa0-9f99b94caf73"),
                            Description = "The Football Is Good For Training And Recreational Purposes",
                            Name = "Tasty Wooden Pants",
                            Price = "95.16"
                        },
                        new
                        {
                            Id = new Guid("891bc6c4-9e41-445a-aa9a-1705e803d97c"),
                            Description = "Andy shoes are designed to keeping in mind durability as well as trends, the most stylish range of shoes & sandals",
                            Name = "Ergonomic Fresh Towels",
                            Price = "521.93"
                        },
                        new
                        {
                            Id = new Guid("76175ffd-f04c-4e9a-bf5f-2c7d77e2b2a3"),
                            Description = "Andy shoes are designed to keeping in mind durability as well as trends, the most stylish range of shoes & sandals",
                            Name = "Handcrafted Soft Computer",
                            Price = "571.16"
                        },
                        new
                        {
                            Id = new Guid("a88e00c1-22a0-4284-b500-28927f74bc27"),
                            Description = "Andy shoes are designed to keeping in mind durability as well as trends, the most stylish range of shoes & sandals",
                            Name = "Handcrafted Rubber Cheese",
                            Price = "376.62"
                        },
                        new
                        {
                            Id = new Guid("17437190-0385-4fc9-a3c3-b7eca1aeeb47"),
                            Description = "Andy shoes are designed to keeping in mind durability as well as trends, the most stylish range of shoes & sandals",
                            Name = "Intelligent Soft Table",
                            Price = "67.21"
                        },
                        new
                        {
                            Id = new Guid("7f74a069-9e0d-4fb6-8b0c-136d6285f2c8"),
                            Description = "The beautiful range of Apple Naturalé that has an exciting mix of natural ingredients. With the Goodness of 100% Natural Ingredients",
                            Name = "Ergonomic Frozen Sausages",
                            Price = "852.61"
                        },
                        new
                        {
                            Id = new Guid("48d9474d-5afe-4429-8200-482f5f1fa73c"),
                            Description = "The slim & simple Maple Gaming Keyboard from Dev Byte comes with a sleek body and 7- Color RGB LED Back-lighting for smart functionality",
                            Name = "Gorgeous Cotton Soap",
                            Price = "590.66"
                        },
                        new
                        {
                            Id = new Guid("b2715386-e67c-4e40-90d4-0b160b7eff6b"),
                            Description = "New ABC 13 9370, 13.3, 5th Gen CoreA5-8250U, 8GB RAM, 256GB SSD, power UHD Graphics, OS 10 Home, OS Office A & J 2016",
                            Name = "Generic Metal Shirt",
                            Price = "790.67"
                        },
                        new
                        {
                            Id = new Guid("66c8508d-bac9-4c1c-9bec-bd887a502beb"),
                            Description = "The beautiful range of Apple Naturalé that has an exciting mix of natural ingredients. With the Goodness of 100% Natural Ingredients",
                            Name = "Handmade Steel Chair",
                            Price = "741.27"
                        },
                        new
                        {
                            Id = new Guid("1aa7e2dd-dcba-43e6-a628-7ff1e1bca851"),
                            Description = "New range of formal shirts are designed keeping you in mind. With fits and styling that will make you stand apart",
                            Name = "Fantastic Wooden Gloves",
                            Price = "302.07"
                        },
                        new
                        {
                            Id = new Guid("407b95ca-cd5b-4297-bc2b-c00697b0df59"),
                            Description = "The Apollotech B340 is an affordable wireless mouse with reliable connectivity, 12 months battery life and modern design",
                            Name = "Generic Plastic Salad",
                            Price = "494.11"
                        },
                        new
                        {
                            Id = new Guid("ec4e3258-484a-4124-a341-35185bc3c06c"),
                            Description = "The slim & simple Maple Gaming Keyboard from Dev Byte comes with a sleek body and 7- Color RGB LED Back-lighting for smart functionality",
                            Name = "Intelligent Plastic Salad",
                            Price = "902.81"
                        },
                        new
                        {
                            Id = new Guid("666bb009-7699-4f1a-af63-c77cc051a36a"),
                            Description = "Carbonite web goalkeeper gloves are ergonomically designed to give easy fit",
                            Name = "Small Plastic Shoes",
                            Price = "44.74"
                        },
                        new
                        {
                            Id = new Guid("0e7da4d0-bdd2-4261-9a33-4de0233cd4de"),
                            Description = "The Football Is Good For Training And Recreational Purposes",
                            Name = "Generic Fresh Pizza",
                            Price = "454.12"
                        },
                        new
                        {
                            Id = new Guid("9a07c97b-781e-4df1-a0f1-410746b0e785"),
                            Description = "The beautiful range of Apple Naturalé that has an exciting mix of natural ingredients. With the Goodness of 100% Natural Ingredients",
                            Name = "Fantastic Concrete Chips",
                            Price = "837.21"
                        },
                        new
                        {
                            Id = new Guid("e2ea0a0f-0a31-48f4-a35a-459107b3f46e"),
                            Description = "New ABC 13 9370, 13.3, 5th Gen CoreA5-8250U, 8GB RAM, 256GB SSD, power UHD Graphics, OS 10 Home, OS Office A & J 2016",
                            Name = "Tasty Frozen Shirt",
                            Price = "544.73"
                        },
                        new
                        {
                            Id = new Guid("6c6a2500-e92d-4b77-93e3-75a00ac3d251"),
                            Description = "Ergonomic executive chair upholstered in bonded black leather and PVC padded seat and back for all-day comfort and support",
                            Name = "Practical Cotton Fish",
                            Price = "829.74"
                        },
                        new
                        {
                            Id = new Guid("ba62f464-f04a-4fcc-ae5a-135763ecada8"),
                            Description = "New range of formal shirts are designed keeping you in mind. With fits and styling that will make you stand apart",
                            Name = "Generic Fresh Computer",
                            Price = "43.75"
                        },
                        new
                        {
                            Id = new Guid("56882157-ef94-42de-9d52-c48bec0d018c"),
                            Description = "The Football Is Good For Training And Recreational Purposes",
                            Name = "Small Soft Ball",
                            Price = "901.22"
                        },
                        new
                        {
                            Id = new Guid("276f0776-7870-4858-a135-856b2367f49a"),
                            Description = "The Apollotech B340 is an affordable wireless mouse with reliable connectivity, 12 months battery life and modern design",
                            Name = "Handcrafted Granite Car",
                            Price = "342.19"
                        },
                        new
                        {
                            Id = new Guid("b254e750-15ec-4644-a01e-01561a811e37"),
                            Description = "New ABC 13 9370, 13.3, 5th Gen CoreA5-8250U, 8GB RAM, 256GB SSD, power UHD Graphics, OS 10 Home, OS Office A & J 2016",
                            Name = "Unbranded Fresh Chair",
                            Price = "96.37"
                        },
                        new
                        {
                            Id = new Guid("a816eb31-b920-47ff-a08b-3edc3fa55211"),
                            Description = "The slim & simple Maple Gaming Keyboard from Dev Byte comes with a sleek body and 7- Color RGB LED Back-lighting for smart functionality",
                            Name = "Unbranded Fresh Table",
                            Price = "363.45"
                        },
                        new
                        {
                            Id = new Guid("8bf2b17e-b6ac-49e6-a94e-815b028fcb81"),
                            Description = "Ergonomic executive chair upholstered in bonded black leather and PVC padded seat and back for all-day comfort and support",
                            Name = "Refined Rubber Salad",
                            Price = "392.62"
                        },
                        new
                        {
                            Id = new Guid("5b8aa408-9a7a-4265-9e1d-8ca69e112226"),
                            Description = "The beautiful range of Apple Naturalé that has an exciting mix of natural ingredients. With the Goodness of 100% Natural Ingredients",
                            Name = "Awesome Frozen Table",
                            Price = "326.79"
                        },
                        new
                        {
                            Id = new Guid("67691693-8414-4dc4-a24e-54c1e0fdad31"),
                            Description = "Carbonite web goalkeeper gloves are ergonomically designed to give easy fit",
                            Name = "Sleek Cotton Hat",
                            Price = "428.92"
                        },
                        new
                        {
                            Id = new Guid("7b2e0079-33ae-41f5-8e19-560b1741a4ae"),
                            Description = "The beautiful range of Apple Naturalé that has an exciting mix of natural ingredients. With the Goodness of 100% Natural Ingredients",
                            Name = "Incredible Cotton Pizza",
                            Price = "573.17"
                        },
                        new
                        {
                            Id = new Guid("ba460e59-92d9-4170-8da0-61d2c423cb13"),
                            Description = "The slim & simple Maple Gaming Keyboard from Dev Byte comes with a sleek body and 7- Color RGB LED Back-lighting for smart functionality",
                            Name = "Sleek Granite Table",
                            Price = "444.09"
                        },
                        new
                        {
                            Id = new Guid("a8690b96-3a40-419f-9266-4d1a3308de4c"),
                            Description = "New ABC 13 9370, 13.3, 5th Gen CoreA5-8250U, 8GB RAM, 256GB SSD, power UHD Graphics, OS 10 Home, OS Office A & J 2016",
                            Name = "Licensed Cotton Chips",
                            Price = "797.01"
                        },
                        new
                        {
                            Id = new Guid("006c5c42-62ca-4604-a08b-63429fc47fce"),
                            Description = "The automobile layout consists of a front-engine design, with transaxle-type transmissions mounted at the rear of the engine and four wheel drive",
                            Name = "Refined Concrete Hat",
                            Price = "901.33"
                        },
                        new
                        {
                            Id = new Guid("eabd4ad1-3e02-46fc-9c8e-d3f14fdf692a"),
                            Description = "The beautiful range of Apple Naturalé that has an exciting mix of natural ingredients. With the Goodness of 100% Natural Ingredients",
                            Name = "Generic Soft Bacon",
                            Price = "217.31"
                        },
                        new
                        {
                            Id = new Guid("a2969bf9-3bf5-4f23-bbe7-c1e325664d07"),
                            Description = "The Apollotech B340 is an affordable wireless mouse with reliable connectivity, 12 months battery life and modern design",
                            Name = "Refined Plastic Shirt",
                            Price = "954.55"
                        },
                        new
                        {
                            Id = new Guid("85cda0e5-c5d0-4b4d-92b0-dcd5ab0361ee"),
                            Description = "The beautiful range of Apple Naturalé that has an exciting mix of natural ingredients. With the Goodness of 100% Natural Ingredients",
                            Name = "Generic Concrete Tuna",
                            Price = "62.18"
                        },
                        new
                        {
                            Id = new Guid("98df2ff4-1adf-4c2b-b6a0-fe41d99612c0"),
                            Description = "The Apollotech B340 is an affordable wireless mouse with reliable connectivity, 12 months battery life and modern design",
                            Name = "Gorgeous Wooden Soap",
                            Price = "306.73"
                        },
                        new
                        {
                            Id = new Guid("2ea13d61-8095-4860-88d7-73a4ae30903d"),
                            Description = "Carbonite web goalkeeper gloves are ergonomically designed to give easy fit",
                            Name = "Sleek Frozen Pants",
                            Price = "451.26"
                        },
                        new
                        {
                            Id = new Guid("7ffd8abe-874c-46b2-9be7-2dc4004e1e45"),
                            Description = "Ergonomic executive chair upholstered in bonded black leather and PVC padded seat and back for all-day comfort and support",
                            Name = "Fantastic Frozen Ball",
                            Price = "985.07"
                        },
                        new
                        {
                            Id = new Guid("536bd696-c455-4893-a25f-26392b41d3c4"),
                            Description = "The beautiful range of Apple Naturalé that has an exciting mix of natural ingredients. With the Goodness of 100% Natural Ingredients",
                            Name = "Unbranded Cotton Ball",
                            Price = "187.52"
                        },
                        new
                        {
                            Id = new Guid("3870dff0-1d25-4bfc-8179-c61294924dbb"),
                            Description = "Andy shoes are designed to keeping in mind durability as well as trends, the most stylish range of shoes & sandals",
                            Name = "Gorgeous Steel Bike",
                            Price = "542.09"
                        },
                        new
                        {
                            Id = new Guid("9628a2f2-98a6-4114-b089-bf4217538ef7"),
                            Description = "Andy shoes are designed to keeping in mind durability as well as trends, the most stylish range of shoes & sandals",
                            Name = "Tasty Steel Ball",
                            Price = "991.05"
                        },
                        new
                        {
                            Id = new Guid("44543f72-ede7-49c3-9a02-8d1283a23f5e"),
                            Description = "The slim & simple Maple Gaming Keyboard from Dev Byte comes with a sleek body and 7- Color RGB LED Back-lighting for smart functionality",
                            Name = "Sleek Plastic Chicken",
                            Price = "150.65"
                        },
                        new
                        {
                            Id = new Guid("e7b7bde1-e8aa-4a44-bb9e-3f71dd4de034"),
                            Description = "New ABC 13 9370, 13.3, 5th Gen CoreA5-8250U, 8GB RAM, 256GB SSD, power UHD Graphics, OS 10 Home, OS Office A & J 2016",
                            Name = "Unbranded Frozen Gloves",
                            Price = "316.39"
                        },
                        new
                        {
                            Id = new Guid("e12a8de8-fc2f-4bcf-b561-3c87f463716b"),
                            Description = "New ABC 13 9370, 13.3, 5th Gen CoreA5-8250U, 8GB RAM, 256GB SSD, power UHD Graphics, OS 10 Home, OS Office A & J 2016",
                            Name = "Handcrafted Cotton Chicken",
                            Price = "876.80"
                        },
                        new
                        {
                            Id = new Guid("512d6b22-9858-4473-aa2f-836bceab4b0b"),
                            Description = "Boston's most advanced compression wear technology increases muscle oxygenation, stabilizes active muscles",
                            Name = "Handcrafted Steel Salad",
                            Price = "350.08"
                        },
                        new
                        {
                            Id = new Guid("cb8fbee9-bebb-4612-bfd4-a9e5c3408713"),
                            Description = "The slim & simple Maple Gaming Keyboard from Dev Byte comes with a sleek body and 7- Color RGB LED Back-lighting for smart functionality",
                            Name = "Handmade Soft Salad",
                            Price = "445.19"
                        },
                        new
                        {
                            Id = new Guid("ad8aff89-4e11-4b15-9ea7-f300e43e217b"),
                            Description = "The Nagasaki Lander is the trademarked name of several series of Nagasaki sport bikes, that started with the 1984 ABC800J",
                            Name = "Licensed Frozen Shoes",
                            Price = "620.49"
                        },
                        new
                        {
                            Id = new Guid("55079c16-7ae0-4cd0-9261-e06be6693455"),
                            Description = "The automobile layout consists of a front-engine design, with transaxle-type transmissions mounted at the rear of the engine and four wheel drive",
                            Name = "Ergonomic Concrete Tuna",
                            Price = "200.79"
                        },
                        new
                        {
                            Id = new Guid("1953eab9-48a5-4877-8164-21213c09f633"),
                            Description = "The Apollotech B340 is an affordable wireless mouse with reliable connectivity, 12 months battery life and modern design",
                            Name = "Unbranded Concrete Chair",
                            Price = "809.50"
                        },
                        new
                        {
                            Id = new Guid("b9901066-6fa4-4998-8b5f-d75363a16d5a"),
                            Description = "Boston's most advanced compression wear technology increases muscle oxygenation, stabilizes active muscles",
                            Name = "Unbranded Rubber Chair",
                            Price = "444.32"
                        },
                        new
                        {
                            Id = new Guid("5c56912d-7459-4afb-b4ff-304a50ed5b04"),
                            Description = "The slim & simple Maple Gaming Keyboard from Dev Byte comes with a sleek body and 7- Color RGB LED Back-lighting for smart functionality",
                            Name = "Handcrafted Soft Table",
                            Price = "627.53"
                        },
                        new
                        {
                            Id = new Guid("f6e7c7ba-6b77-4207-8789-6de2ff5b290f"),
                            Description = "The beautiful range of Apple Naturalé that has an exciting mix of natural ingredients. With the Goodness of 100% Natural Ingredients",
                            Name = "Gorgeous Plastic Gloves",
                            Price = "446.65"
                        },
                        new
                        {
                            Id = new Guid("40010837-9b5b-4c4f-97a0-ea32c8e16e43"),
                            Description = "Carbonite web goalkeeper gloves are ergonomically designed to give easy fit",
                            Name = "Intelligent Rubber Car",
                            Price = "771.85"
                        },
                        new
                        {
                            Id = new Guid("5cdf4ea8-d493-4166-b101-10190c4bd5f3"),
                            Description = "New range of formal shirts are designed keeping you in mind. With fits and styling that will make you stand apart",
                            Name = "Gorgeous Frozen Car",
                            Price = "52.57"
                        },
                        new
                        {
                            Id = new Guid("444291ea-f052-4c08-9456-956bf5fc3cb4"),
                            Description = "Carbonite web goalkeeper gloves are ergonomically designed to give easy fit",
                            Name = "Practical Granite Chicken",
                            Price = "838.22"
                        },
                        new
                        {
                            Id = new Guid("8fa586fc-5351-40ad-b347-0a2a3b1d7f1e"),
                            Description = "Carbonite web goalkeeper gloves are ergonomically designed to give easy fit",
                            Name = "Sleek Soft Gloves",
                            Price = "549.34"
                        },
                        new
                        {
                            Id = new Guid("814d50d7-d8a1-45f9-8985-4874fcef6f99"),
                            Description = "Andy shoes are designed to keeping in mind durability as well as trends, the most stylish range of shoes & sandals",
                            Name = "Licensed Plastic Computer",
                            Price = "967.27"
                        },
                        new
                        {
                            Id = new Guid("566a675a-eef1-425f-a516-9bb64bb6bd05"),
                            Description = "Andy shoes are designed to keeping in mind durability as well as trends, the most stylish range of shoes & sandals",
                            Name = "Small Concrete Bike",
                            Price = "545.38"
                        },
                        new
                        {
                            Id = new Guid("24ff8308-81cf-4b1b-a650-c3f0ac5fb872"),
                            Description = "New ABC 13 9370, 13.3, 5th Gen CoreA5-8250U, 8GB RAM, 256GB SSD, power UHD Graphics, OS 10 Home, OS Office A & J 2016",
                            Name = "Gorgeous Wooden Chicken",
                            Price = "793.31"
                        },
                        new
                        {
                            Id = new Guid("8be82d3f-adf8-4241-9560-2b7d634d75fa"),
                            Description = "The Football Is Good For Training And Recreational Purposes",
                            Name = "Fantastic Granite Cheese",
                            Price = "520.44"
                        },
                        new
                        {
                            Id = new Guid("2524dccd-9ae8-4c74-9260-8d4d652e752b"),
                            Description = "Carbonite web goalkeeper gloves are ergonomically designed to give easy fit",
                            Name = "Rustic Soft Chips",
                            Price = "562.43"
                        },
                        new
                        {
                            Id = new Guid("c65a0386-0922-4ea9-98bd-6ba4ccf05744"),
                            Description = "The Nagasaki Lander is the trademarked name of several series of Nagasaki sport bikes, that started with the 1984 ABC800J",
                            Name = "Ergonomic Soft Bacon",
                            Price = "388.69"
                        },
                        new
                        {
                            Id = new Guid("6498309c-060b-436d-9d86-1c5c37181a51"),
                            Description = "New range of formal shirts are designed keeping you in mind. With fits and styling that will make you stand apart",
                            Name = "Handmade Granite Gloves",
                            Price = "899.58"
                        },
                        new
                        {
                            Id = new Guid("623edeb5-2562-436a-9049-7b2a28d887e2"),
                            Description = "Carbonite web goalkeeper gloves are ergonomically designed to give easy fit",
                            Name = "Gorgeous Soft Pizza",
                            Price = "211.59"
                        },
                        new
                        {
                            Id = new Guid("cba0d752-732a-499d-9198-09e81c5e5a30"),
                            Description = "Carbonite web goalkeeper gloves are ergonomically designed to give easy fit",
                            Name = "Awesome Soft Shoes",
                            Price = "713.44"
                        },
                        new
                        {
                            Id = new Guid("e8fd5ec8-adcf-4126-bc3e-732d155c1b6f"),
                            Description = "Ergonomic executive chair upholstered in bonded black leather and PVC padded seat and back for all-day comfort and support",
                            Name = "Tasty Cotton Chair",
                            Price = "119.75"
                        },
                        new
                        {
                            Id = new Guid("02eea13c-c632-4077-8f09-186371d87738"),
                            Description = "The Apollotech B340 is an affordable wireless mouse with reliable connectivity, 12 months battery life and modern design",
                            Name = "Gorgeous Wooden Tuna",
                            Price = "189.20"
                        },
                        new
                        {
                            Id = new Guid("2f247d47-2149-43b5-88e9-f06bfc73e8c7"),
                            Description = "Andy shoes are designed to keeping in mind durability as well as trends, the most stylish range of shoes & sandals",
                            Name = "Unbranded Fresh Towels",
                            Price = "998.09"
                        },
                        new
                        {
                            Id = new Guid("cce5cc97-8c1d-440c-9ed6-e19c2fda83c1"),
                            Description = "Carbonite web goalkeeper gloves are ergonomically designed to give easy fit",
                            Name = "Gorgeous Soft Computer",
                            Price = "460.65"
                        },
                        new
                        {
                            Id = new Guid("1326ef6c-2446-4023-a0e4-5ccce1c4cc84"),
                            Description = "New ABC 13 9370, 13.3, 5th Gen CoreA5-8250U, 8GB RAM, 256GB SSD, power UHD Graphics, OS 10 Home, OS Office A & J 2016",
                            Name = "Awesome Soft Table",
                            Price = "819.99"
                        },
                        new
                        {
                            Id = new Guid("81d5a9df-6351-4618-929c-fc0f5d7bc6dd"),
                            Description = "Andy shoes are designed to keeping in mind durability as well as trends, the most stylish range of shoes & sandals",
                            Name = "Sleek Frozen Keyboard",
                            Price = "983.63"
                        },
                        new
                        {
                            Id = new Guid("8b413dbd-8272-4ef7-95eb-d58b2c83d40e"),
                            Description = "New range of formal shirts are designed keeping you in mind. With fits and styling that will make you stand apart",
                            Name = "Tasty Plastic Chair",
                            Price = "798.04"
                        },
                        new
                        {
                            Id = new Guid("84f2aaea-f131-41f6-b765-efa7c7fe85de"),
                            Description = "New ABC 13 9370, 13.3, 5th Gen CoreA5-8250U, 8GB RAM, 256GB SSD, power UHD Graphics, OS 10 Home, OS Office A & J 2016",
                            Name = "Gorgeous Cotton Gloves",
                            Price = "992.13"
                        },
                        new
                        {
                            Id = new Guid("7eaed778-e52e-4e5d-bf27-7dea55ee0383"),
                            Description = "The Nagasaki Lander is the trademarked name of several series of Nagasaki sport bikes, that started with the 1984 ABC800J",
                            Name = "Practical Metal Car",
                            Price = "484.64"
                        },
                        new
                        {
                            Id = new Guid("d266e84e-9119-4cd3-a893-356ae870bb32"),
                            Description = "Ergonomic executive chair upholstered in bonded black leather and PVC padded seat and back for all-day comfort and support",
                            Name = "Rustic Concrete Salad",
                            Price = "701.75"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
